import type { QuizQuestion } from "../types.ts";

export const htmlQuestions: QuizQuestion[] = [
  {
    id: 121,
    type: "single",
    topic: "html",
    difficulty: "easy",
    prompt: "What does HTML stand for?",
    options: [
      { id: "a", label: "HyperText Markup Language" },
      { id: "b", label: "High-Level Text Machine Language" },
      { id: "c", label: "Hyperlink and Text Managing Language" },
      { id: "d", label: "Home Tool Markup Language" },
    ],
    correctId: "a",
    explanation: "HTML is HyperText Markup Language — structure for web documents.",
  },
  {
    id: 122,
    type: "single",
    topic: "html",
    difficulty: "easy",
    prompt: "Which element is the correct way to create a top-level page heading?",
    options: [
      { id: "a", label: "<heading>" },
      { id: "b", label: "<h1>" },
      { id: "c", label: "<head>" },
      { id: "d", label: "<title>" },
    ],
    correctId: "b",
    explanation: "`<h1>`–`<h6>` are headings; `<head>` is metadata; `<title>` is the document title.",
  },
  {
    id: 123,
    type: "single",
    topic: "html",
    difficulty: "medium",
    prompt: "Which attribute provides alternative text for an image?",
    options: [
      { id: "a", label: "title" },
      { id: "b", label: "alt" },
      { id: "c", label: "caption" },
      { id: "d", label: "aria-image" },
    ],
    correctId: "b",
    explanation: "`alt` describes the image for accessibility and when the image fails to load.",
  },
  {
    id: 124,
    type: "single",
    topic: "html",
    difficulty: "medium",
    prompt: "What is the difference between `<div>` and `<section>`?",
    options: [
      { id: "a", label: "No difference; browsers forbid section" },
      { id: "b", label: "section is semantic for a thematic grouping; div is generic flow content" },
      { id: "c", label: "div is only allowed in <head>" },
      { id: "d", label: "section cannot contain headings" },
    ],
    correctId: "b",
    explanation: "Prefer semantic elements when they match meaning; use `div` when no better element fits.",
  },
  {
    id: 125,
    type: "single",
    topic: "html",
    difficulty: "hard",
    prompt: "Which element associates a text label with a form control for accessibility?",
    options: [
      { id: "a", label: "<span>" },
      { id: "b", label: "<label>" },
      { id: "c", label: "<meta>" },
      { id: "d", label: "<legend> without fieldset" },
    ],
    correctId: "b",
    explanation: "`<label for=\"id\">` or wrapping the control improves hit targets and AT support.",
  },
  {
    id: 126,
    type: "multi",
    topic: "html",
    difficulty: "easy",
    prompt: "Which are valid HTML5 semantic elements? (select all)",
    options: [
      { id: "a", label: "<header>" },
      { id: "b", label: "<nav>" },
      { id: "c", label: "<blink>" },
      { id: "d", label: "<main>" },
      { id: "e", label: "<footer>" },
    ],
    correctIds: ["a", "b", "d", "e"],
    explanation: "`<blink>` is obsolete/non-standard for modern HTML5 semantics.",
  },
  {
    id: 127,
    type: "multi",
    topic: "html",
    difficulty: "medium",
    prompt: "Which input types are valid in HTML5? (select all)",
    options: [
      { id: "a", label: "email" },
      { id: "b", label: "date" },
      { id: "c", label: "password" },
      { id: "d", label: "regex" },
    ],
    correctIds: ["a", "b", "c"],
    explanation: "There is no `type=\"regex\"`; use `pattern` for regex validation on text-like inputs.",
  },
  {
    id: 128,
    type: "multi",
    topic: "html",
    difficulty: "medium",
    prompt: "Which attributes improve link/image accessibility or behavior? (select all)",
    options: [
      { id: "a", label: "alt on <img>" },
      { id: "b", label: "rel=\"noopener\" with target=\"_blank\"" },
      { id: "c", label: "href on <a>" },
      { id: "d", label: "onclick as a substitute for href for navigation" },
    ],
    correctIds: ["a", "b", "c"],
    explanation: "Prefer real links with href; noopener mitigates tab-nabbing with _blank.",
  },
  {
    id: 129,
    type: "boolean",
    topic: "html",
    difficulty: "easy",
    prompt: "The `<title>` element belongs in the document `<head>`.",
    correct: true,
    explanation: "Document metadata including title lives in `<head>`.",
  },
  {
    id: 130,
    type: "boolean",
    topic: "html",
    difficulty: "medium",
    prompt: "Block-level elements like `<p>` may legally contain other `<p>` elements nested inside.",
    correct: false,
    explanation: "A `<p>` cannot contain block-level peers like another `<p>`; the browser will auto-close.",
  },
  {
    id: 131,
    type: "boolean",
    topic: "html",
    difficulty: "easy",
    prompt: "`<img>` is a void (empty) element and does not use a closing tag.",
    correct: true,
    explanation: "Void elements include img, br, hr, input, meta, link, etc.",
  },
  {
    id: 132,
    type: "fill",
    topic: "html",
    difficulty: "easy",
    prompt: "What attribute on `<a>` specifies the destination URL?",
    accept: ["href"],
    placeholder: "attribute name",
    explanation: "`href` holds the hyperlink reference.",
  },
  {
    id: 133,
    type: "fill",
    topic: "html",
    difficulty: "medium",
    prompt: "Which element embeds a self-contained composition like a diagram with optional caption (`<figcaption>`)?",
    accept: ["figure", "<figure>"],
    explanation: "`<figure>` groups media/code with an optional `<figcaption>`.",
  },
  {
    id: 134,
    type: "fill",
    topic: "html",
    difficulty: "easy",
    prompt: "What is the root element of an HTML document?",
    accept: ["html", "<html>"],
    explanation: "Documents start with `<!DOCTYPE html>` then `<html>`.",
  },
  {
    id: 135,
    type: "order",
    topic: "html",
    difficulty: "easy",
    prompt: "Order these document skeleton pieces from outermost / earliest to innermost body content:",
    items: [
      { id: "doctype", label: "<!DOCTYPE html>" },
      { id: "html", label: "<html>" },
      { id: "body", label: "<body>" },
      { id: "main", label: "<main> content" },
    ],
    correctOrder: ["doctype", "html", "body", "main"],
    explanation: "Doctype, html root, then head/body; main is primary content inside body.",
  },
  {
    id: 136,
    type: "order",
    topic: "html",
    difficulty: "medium",
    prompt: "Order a typical accessible form field structure:",
    items: [
      { id: "label", label: "<label for=\"email\">Email</label>" },
      { id: "input", label: "<input id=\"email\" type=\"email\">" },
      { id: "error", label: "Inline error/help text referenced via aria-describedby" },
    ],
    correctOrder: ["label", "input", "error"],
    explanation: "Label association first, then control, then supporting text/errors.",
  },
  {
    id: 137,
    type: "snippet",
    topic: "html",
    difficulty: "easy",
    prompt: "Which snippet correctly links to an external stylesheet?",
    snippets: [
      { id: "a", code: `<link rel="stylesheet" href="/styles.css">` },
      { id: "b", code: `<style src="/styles.css"></style>` },
      { id: "c", code: `<stylesheet href="/styles.css"></stylesheet>` },
    ],
    correctId: "a",
    explanation: "Use `<link rel=\"stylesheet\" href=\"...\">` in the head.",
  },
  {
    id: 138,
    type: "snippet",
    topic: "html",
    difficulty: "medium",
    prompt: "Which snippet is the more accessible button for an action (not navigation)?",
    snippets: [
      { id: "a", code: `<button type="button">Save</button>` },
      { id: "b", code: `<div onclick="save()">Save</div>` },
      { id: "c", code: `<a href="#" onclick="save()">Save</a>` },
    ],
    correctId: "a",
    explanation: "Use `<button>` for actions; links are for navigation. Divs lack keyboard semantics by default.",
  },
  {
    id: 139,
    type: "match",
    topic: "html",
    difficulty: "easy",
    prompt: "Match each element to its purpose.",
    left: [
      { id: "a", label: "<a>" },
      { id: "ul", label: "<ul>" },
      { id: "table", label: "<table>" },
      { id: "form", label: "<form>" },
    ],
    right: [
      { id: "r1", label: "hyperlink" },
      { id: "r2", label: "unordered list" },
      { id: "r3", label: "tabular data" },
      { id: "r4", label: "group controls for submission" },
    ],
    pairs: { a: "r1", ul: "r2", table: "r3", form: "r4" },
  },
  {
    id: 140,
    type: "match",
    topic: "html",
    difficulty: "medium",
    prompt: "Match each attribute to its role.",
    left: [
      { id: "id", label: "id" },
      { id: "class", label: "class" },
      { id: "required", label: "required" },
      { id: "placeholder", label: "placeholder" },
    ],
    right: [
      { id: "r1", label: "unique identifier in the document" },
      { id: "r2", label: "space-separated styling/scripting hooks" },
      { id: "r3", label: "form field must be filled before submit" },
      { id: "r4", label: "hint text inside empty fields (not a label)" },
    ],
    pairs: { id: "r1", class: "r2", required: "r3", placeholder: "r4" },
  },
  {
    id: 141,
    type: "hotspot",
    topic: "html",
    difficulty: "medium",
    prompt: "Click the line with an accessibility problem for the image.",
    code: `<article>
  <h2>Team photo</h2>
  <img src="/team.jpg">
  <p>Our engineering team</p>
</article>`,
    regions: [
      { id: "r1", label: "Line 1: article", startLine: 1, endLine: 1 },
      { id: "r2", label: "Line 2: heading", startLine: 2, endLine: 2 },
      { id: "r3", label: "Line 3: img missing alt", startLine: 3, endLine: 3 },
      { id: "r4", label: "Line 4: paragraph", startLine: 4, endLine: 4 },
    ],
    correctRegionId: "r3",
    explanation: "Images need an appropriate `alt` attribute (or empty alt if decorative).",
  },
  {
    id: 142,
    type: "hotspot",
    topic: "html",
    difficulty: "hard",
    prompt: "Click the line that should use a semantic landmark instead of a generic container for primary navigation.",
    code: `<div id="nav">
  <a href="/">Home</a>
  <a href="/about">About</a>
</div>
<main>Content</main>`,
    regions: [
      { id: "r1", label: "Line 1: div#nav instead of nav", startLine: 1, endLine: 1 },
      { id: "r2", label: "Line 2: home link", startLine: 2, endLine: 2 },
      { id: "r3", label: "Line 3: about link", startLine: 3, endLine: 3 },
      { id: "r4", label: "Line 5: main", startLine: 5, endLine: 5 },
    ],
    correctRegionId: "r1",
    explanation: "Prefer `<nav>` for major navigation landmarks instead of a generic `div`.",
  },
  {
    id: 143,
    type: "output",
    topic: "html",
    difficulty: "easy",
    prompt: "What visible text does this produce? (type the text only)",
    code: `<p>Hello <strong>world</strong></p>`,
    accept: ["Hello world"],
    explanation: "Strong emphasizes but the text content is still \"Hello world\".",
  },
  {
    id: 144,
    type: "output",
    topic: "html",
    difficulty: "medium",
    prompt: "How many list items will render?",
    code: `<ul>
  <li>One</li>
  <li>Two</li>
  <li>Three</li>
</ul>`,
    accept: ["3", "three"],
    explanation: "Three `<li>` elements → three items.",
  },
  {
    id: 145,
    type: "single",
    topic: "html",
    difficulty: "hard",
    prompt: "What does the `defer` attribute on a `<script>` tag do?",
    options: [
      { id: "a", label: "Downloads the script in parallel and executes after the document is parsed" },
      { id: "b", label: "Prevents the script from ever running" },
      { id: "c", label: "Runs the script before any HTML is parsed" },
      { id: "d", label: "Only works for inline scripts" },
    ],
    correctId: "a",
    explanation: "`defer` is for external scripts: download in parallel, run in order after HTML parse.",
  },
];
