import type { QuizQuestion } from "../types.ts";

export const javascriptQuestions: QuizQuestion[] = [
  {
    id: 1,
    type: "single",
    topic: "javascript",
    difficulty: "easy",
    prompt: "Which keyword declares a block-scoped variable that cannot be reassigned?",
    options: [
      { id: "a", label: "var" },
      { id: "b", label: "let" },
      { id: "c", label: "const" },
      { id: "d", label: "static" },
    ],
    correctId: "c",
    explanation:
      "`const` is block-scoped and forbids reassignment of the binding (the value may still be mutated if it is an object).",
  },
  {
    id: 2,
    type: "single",
    topic: "javascript",
    difficulty: "easy",
    prompt: "What does `typeof null` return in JavaScript?",
    options: [
      { id: "a", label: '"null"' },
      { id: "b", label: '"object"' },
      { id: "c", label: '"undefined"' },
      { id: "d", label: '"boolean"' },
    ],
    correctId: "b",
    explanation:
      "A long-standing language quirk: `typeof null` is `\"object\"`. Prefer strict equality checks for null.",
  },
  {
    id: 3,
    type: "single",
    topic: "javascript",
    difficulty: "medium",
    prompt: "What is the result of `[] == false`?",
    options: [
      { id: "a", label: "true" },
      { id: "b", label: "false" },
      { id: "c", label: "TypeError" },
      { id: "d", label: "undefined" },
    ],
    correctId: "a",
    hint: "Think about ToPrimitive and ToNumber coercion under ==.",
    explanation:
      "With `==`, both sides are coerced: `[]` becomes `\"\"` then `0`, and `false` becomes `0`, so they compare equal. Prefer `===`.",
  },
  {
    id: 4,
    type: "single",
    topic: "javascript",
    difficulty: "medium",
    prompt: "Which method creates a new array with the results of calling a function on every element?",
    options: [
      { id: "a", label: "forEach" },
      { id: "b", label: "map" },
      { id: "c", label: "filter" },
      { id: "d", label: "reduce" },
    ],
    correctId: "b",
    explanation: "`map` returns a new array of transformed values; `forEach` returns undefined.",
  },
  {
    id: 5,
    type: "single",
    topic: "javascript",
    difficulty: "hard",
    prompt: "What is printed?\n\n```js\nconsole.log(typeof (() => {}));\n```",
    options: [
      { id: "a", label: '"object"' },
      { id: "b", label: '"function"' },
      { id: "c", label: '"arrow"' },
      { id: "d", label: '"undefined"' },
    ],
    correctId: "b",
    explanation: "Functions (including arrow functions) have typeof `\"function\"`.",
  },
  {
    id: 6,
    type: "multi",
    topic: "javascript",
    difficulty: "easy",
    prompt: "Which of the following are falsy values in JavaScript? (select all)",
    options: [
      { id: "a", label: "0" },
      { id: "b", label: '"" (empty string)' },
      { id: "c", label: "[]" },
      { id: "d", label: "null" },
      { id: "e", label: "{}" },
    ],
    correctIds: ["a", "b", "d"],
    explanation: "Falsy: false, 0, -0, 0n, \"\", null, undefined, NaN. Empty arrays and objects are truthy.",
  },
  {
    id: 7,
    type: "multi",
    topic: "javascript",
    difficulty: "medium",
    prompt: "Which array methods mutate the original array? (select all)",
    options: [
      { id: "a", label: "push" },
      { id: "b", label: "map" },
      { id: "c", label: "splice" },
      { id: "d", label: "slice" },
      { id: "e", label: "sort" },
    ],
    correctIds: ["a", "c", "e"],
    explanation: "`push`, `splice`, and `sort` mutate in place. `map` and `slice` return new arrays.",
  },
  {
    id: 8,
    type: "multi",
    topic: "javascript",
    difficulty: "medium",
    prompt: "Which statements about Promises are correct? (select all)",
    options: [
      { id: "a", label: "A Promise can settle only once (fulfill or reject)" },
      { id: "b", label: ".then always returns a new Promise" },
      { id: "c", label: "await can only be used at the top level of a module or inside async functions" },
      { id: "d", label: "Promise.all rejects only after every promise rejects" },
    ],
    correctIds: ["a", "b", "c"],
    explanation: "`Promise.all` rejects on the first rejection; it does not wait for all to fail.",
  },
  {
    id: 9,
    type: "boolean",
    topic: "javascript",
    difficulty: "easy",
    prompt: "JavaScript's main execution model is single-threaded with an event loop.",
    correct: true,
    explanation:
      "JS runs on one call stack; async work is scheduled via the event loop (and Web APIs / libuv in Node).",
  },
  {
    id: 10,
    type: "boolean",
    topic: "javascript",
    difficulty: "medium",
    prompt: "`==` and `===` always produce the same result for any pair of values.",
    correct: false,
    explanation: "`==` performs type coercion; `===` does not. Example: `0 == \"0\"` is true, `0 === \"0\"` is false.",
  },
  {
    id: 11,
    type: "boolean",
    topic: "javascript",
    difficulty: "easy",
    prompt: "`const` prevents mutation of object properties.",
    correct: false,
    explanation:
      "`const` only prevents rebinding the variable. Object properties and array elements can still change unless frozen.",
  },
  {
    id: 12,
    type: "fill",
    topic: "javascript",
    difficulty: "easy",
    prompt: "What keyword is used to declare a function that always returns a Promise and allows `await` inside?",
    accept: ["async"],
    placeholder: "one keyword",
    explanation: "`async function` (or async arrow) enables `await` and wraps the return value in a Promise.",
  },
  {
    id: 13,
    type: "fill",
    topic: "javascript",
    difficulty: "medium",
    prompt: "Complete: `JSON.____(obj)` converts a JavaScript value to a JSON string.",
    accept: ["stringify"],
    placeholder: "method name",
    explanation: "`JSON.stringify` serializes; `JSON.parse` deserializes.",
  },
  {
    id: 14,
    type: "fill",
    topic: "javascript",
    difficulty: "easy",
    prompt: "What is the value of an uninitialized `let` variable before assignment? (one word)",
    accept: ["undefined"],
    explanation: "Declared `let`/`const` bindings exist in the TDZ until initialized; after init without value, `let` is undefined. Uninitialized read throws; default value concept is undefined.",
  },
  {
    id: 15,
    type: "order",
    topic: "javascript",
    difficulty: "medium",
    prompt: "Order these microtask / macrotask events from earliest to latest after a sync script finishes:",
    items: [
      { id: "sync", label: "Synchronous code finishes" },
      { id: "promise", label: "Promise.then callback (microtask)" },
      { id: "timeout", label: "setTimeout(fn, 0) callback (macrotask)" },
    ],
    correctOrder: ["sync", "promise", "timeout"],
    explanation: "After the current stack, the microtask queue (Promises) drains before the next macrotask (timer).",
  },
  {
    id: 16,
    type: "order",
    topic: "javascript",
    difficulty: "easy",
    prompt: "Order the typical steps to handle a successful async fetch of JSON:",
    items: [
      { id: "fetch", label: "fetch(url)" },
      { id: "res", label: "await response.json()" },
      { id: "use", label: "use the parsed data" },
    ],
    correctOrder: ["fetch", "res", "use"],
    explanation: "Get a Response, parse the body, then work with the data.",
  },
  {
    id: 17,
    type: "snippet",
    topic: "javascript",
    difficulty: "medium",
    prompt: "Which snippet correctly checks if a value is a non-null object (not an array)?",
    snippets: [
      {
        id: "a",
        code: `typeof value === "object" && value !== null && !Array.isArray(value)`,
      },
      {
        id: "b",
        code: `typeof value === "object"`,
      },
      {
        id: "c",
        code: `value instanceof Object && value.length === undefined`,
      },
    ],
    correctId: "a",
    explanation:
      "`typeof null` is object and arrays are objects; exclude both for a plain non-null, non-array object check.",
  },
  {
    id: 18,
    type: "snippet",
    topic: "javascript",
    difficulty: "easy",
    prompt: "Which snippet correctly deep-clones a plain JSON-safe object (no functions/dates/maps)?",
    snippets: [
      { id: "a", code: `const copy = { ...obj };` },
      { id: "b", code: `const copy = JSON.parse(JSON.stringify(obj));` },
      { id: "c", code: `const copy = obj;` },
    ],
    correctId: "b",
    explanation:
      "Spread is shallow. Assignment shares the reference. JSON round-trip deep-clones JSON-safe data (with known limitations).",
  },
  {
    id: 19,
    type: "match",
    topic: "javascript",
    difficulty: "easy",
    prompt: "Match each array method to what it returns.",
    left: [
      { id: "map", label: "map" },
      { id: "filter", label: "filter" },
      { id: "find", label: "find" },
      { id: "includes", label: "includes" },
    ],
    right: [
      { id: "r1", label: "new array of same length (transformed)" },
      { id: "r2", label: "new array of matching elements" },
      { id: "r3", label: "first matching element or undefined" },
      { id: "r4", label: "boolean" },
    ],
    pairs: { map: "r1", filter: "r2", find: "r3", includes: "r4" },
  },
  {
    id: 20,
    type: "match",
    topic: "javascript",
    difficulty: "medium",
    prompt: "Match each operator / construct to its primary use.",
    left: [
      { id: "spread", label: "... (spread)" },
      { id: "rest", label: "... (rest params)" },
      { id: "opt", label: "?." },
      { id: "nullish", label: "??" },
    ],
    right: [
      { id: "r1", label: "expand iterable into elements/args" },
      { id: "r2", label: "collect remaining args into array" },
      { id: "r3", label: "safe property access when base may be nullish" },
      { id: "r4", label: "default when left is null or undefined" },
    ],
    pairs: { spread: "r1", rest: "r2", opt: "r3", nullish: "r4" },
  },
  {
    id: 21,
    type: "hotspot",
    topic: "javascript",
    difficulty: "medium",
    prompt: "Click the line that throws at runtime.",
    code: `const user = { name: "Ada" };
user.age = 30;
user = { name: "Grace" };
console.log(user.name);`,
    regions: [
      { id: "r1", label: "Line 1: const declaration", startLine: 1, endLine: 1 },
      { id: "r2", label: "Line 2: mutate property", startLine: 2, endLine: 2 },
      { id: "r3", label: "Line 3: reassign const", startLine: 3, endLine: 3 },
      { id: "r4", label: "Line 4: log", startLine: 4, endLine: 4 },
    ],
    correctRegionId: "r3",
    explanation: "Property mutation on a const object is fine; reassigning the binding is not.",
  },
  {
    id: 22,
    type: "hotspot",
    topic: "javascript",
    difficulty: "hard",
    prompt: "Click the line that causes a Temporal Dead Zone ReferenceError.",
    code: `console.log(a);
let a = 1;
var b = 2;
console.log(b);`,
    regions: [
      { id: "r1", label: "Line 1: log a before init", startLine: 1, endLine: 1 },
      { id: "r2", label: "Line 2: let a", startLine: 2, endLine: 2 },
      { id: "r3", label: "Line 3: var b", startLine: 3, endLine: 3 },
      { id: "r4", label: "Line 4: log b", startLine: 4, endLine: 4 },
    ],
    correctRegionId: "r1",
    explanation: "`let`/`const` are in the TDZ until initialized; accessing `a` on line 1 throws.",
  },
  {
    id: 23,
    type: "output",
    topic: "javascript",
    difficulty: "easy",
    prompt: "What is logged?",
    code: `console.log(typeof NaN);`,
    accept: ['"number"', "number"],
    explanation: "`NaN` is of type number (Not-a-Number is still a numeric type).",
  },
  {
    id: 24,
    type: "output",
    topic: "javascript",
    difficulty: "medium",
    prompt: "What is logged?",
    code: `const arr = [1, 2, 3];
console.log(arr.slice(0, 2).join("-"));`,
    accept: ["1-2"],
    explanation: "`slice(0, 2)` yields `[1, 2]`; `join(\"-\")` produces `\"1-2\"`.",
  },
  {
    id: 25,
    type: "output",
    topic: "javascript",
    difficulty: "hard",
    prompt: "What is logged?",
    code: `console.log([1, 2, 3].map(parseInt));`,
    accept: ["1,NaN,NaN", "1, NaN, NaN", "[1, NaN, NaN]", "[1,NaN,NaN]"],
    hint: "map passes (value, index, array). parseInt takes (string, radix).",
    explanation:
      "`parseInt(\"1\", 0)`, `parseInt(\"2\", 1)` (invalid radix → NaN), `parseInt(\"3\", 2)` (invalid binary digit → NaN).",
  },
];
