import type { QuizQuestion } from "../types.ts";

export const nextjsQuestions: QuizQuestion[] = [
  {
    id: 349,
    type: "single",
    topic: "nextjs",
    difficulty: "easy",
    prompt: "Where does Next.js middleware typically run in the request flow?",
    options: [
      { id: "b", label: "Only inside PostgreSQL triggers" },
      { id: "c", label: "After the HTML has been painted for 5 minutes" },
      { id: "d", label: "Inside the user's GPU driver" },
      { id: "a", label: "At the edge, before the matched route renders" },
    ],
    correctId: "a",
    explanation: "Middleware runs early (edge) for redirects, auth gates, headers, etc.",
    illustration: {
      kind: "svg",
      diagram: "nextjs-layers",
      blankFocus: true,
      alt: "Browser, highlighted middle layer, server, and data layers",
      caption: "Where does middleware typically run?",
    },
  },
  {
    id: 350,
    type: "single",
    topic: "nextjs",
    difficulty: "easy",
    prompt: "What is a main benefit of React Server Components in the App Router?",
    options: [
      { id: "c", label: "They force all state into localStorage" },
      { id: "d", label: "They disable CSS" },
      { id: "a", label: "Fetch data on the server and ship less client JavaScript" },
      { id: "b", label: "They replace SQL entirely" },
    ],
    correctId: "a",
    explanation: "RSCs run on the server, keeping secrets and heavy work off the client bundle.",
  },
  {
    id: 351,
    type: "boolean",
    topic: "nextjs",
    difficulty: "easy",
    prompt: "A file that uses useState must be a Client Component (typically with \"use client\").",
    correct: true,
    explanation: "Hooks like useState need a client component boundary.",
  },
  {
    id: 352,
    type: "single",
    topic: "nextjs",
    difficulty: "medium",
    prompt: "What are Route Handlers primarily for in the App Router?",
    options: [
      { id: "a", label: "HTTP endpoints (GET/POST/...) alongside your app routes" },
      { id: "b", label: "Styling SVG icons only" },
      { id: "c", label: "Replacing package.json" },
      { id: "d", label: "Compiling Python" },
    ],
    correctId: "a",
    explanation: "route.ts/js handlers expose HTTP methods for APIs and webhooks.",
    illustration: {
      kind: "svg",
      diagram: "nextjs-layers",
      alt: "Browser, edge, server, and data layers in a Next.js request",
      caption: "Which layer typically hosts route handlers?",
    },
  },
  {
    id: 353,
    type: "single",
    topic: "nextjs",
    difficulty: "medium",
    prompt: "What is special about environment variables prefixed with NEXT_PUBLIC_?",
    options: [
      { id: "b", label: "They can only be read inside PostgreSQL" },
      { id: "c", label: "They are automatically encrypted with a user password" },
      { id: "d", label: "They disable middleware" },
      { id: "a", label: "They are exposed to the browser bundle" },
    ],
    correctId: "a",
    explanation: "Anything NEXT_PUBLIC_ is embedded for client code — never put secrets there.",
  },
  {
    id: 354,
    type: "multi",
    topic: "nextjs",
    difficulty: "medium",
    prompt: "Which values should stay server-only (not NEXT_PUBLIC_)? (select all)",
    options: [
      { id: "a", label: "Database connection URL" },
      { id: "b", label: "Private third-party API secret" },
      { id: "c", label: "Public marketing site URL" },
      { id: "d", label: "Stripe secret key" },
    ],
    correctIds: ["a", "b", "d"],
    explanation: "Public URLs can be public; secrets and DB URLs must not ship to the client.",
  },
  {
    id: 355,
    type: "match",
    topic: "nextjs",
    difficulty: "medium",
    prompt: "Match each Next.js piece to its role.",
    left: [
      { id: "l1", label: "Server Component" },
      { id: "l2", label: "Client Component" },
      { id: "l3", label: "Middleware" },
      { id: "l4", label: "Route Handler" },
    ],
    right: [
      { id: "r1", label: "Render/fetch on the server by default" },
      { id: "r2", label: "Use browser APIs and React state hooks" },
      { id: "r3", label: "Run early for redirects/headers" },
      { id: "r4", label: "Handle HTTP methods as an endpoint" },
    ],
    pairs: { l1: "r1", l2: "r2", l3: "r3", l4: "r4" },
    explanation: "Knowing which layer owns which job prevents leaking secrets and bloating bundles.",
  },
  {
    id: 356,
    type: "order",
    topic: "nextjs",
    difficulty: "medium",
    prompt: "Order a typical App Router data path (first → last).",
    items: [
      { id: "browser", label: "Browser request" },
      { id: "middleware", label: "Middleware (edge)" },
      { id: "rsc", label: "Server Component / route" },
      { id: "db", label: "Database / external API" },
    ],
    correctOrder: ["browser", "middleware", "rsc", "db"],
    explanation: "Middleware can short-circuit; otherwise server code talks to data sources.",
    illustration: {
      kind: "svg",
      diagram: "nextjs-layers",
      blankLabels: true,
      alt: "Four unlabeled Next.js request layers left to right",
      caption: "Match each step to positions 1→4",
    },
  },
  {
    id: 357,
    type: "single",
    topic: "nextjs",
    difficulty: "medium",
    prompt: "In Next.js caching discussions, what does revalidate generally control?",
    options: [
      { id: "b", label: "The Postgres vacuum schedule" },
      { id: "c", label: "The color of 404 pages only" },
      { id: "d", label: "Whether TypeScript is enabled" },
      { id: "a", label: "How long cached data may be reused before refreshing" },
    ],
    correctId: "a",
    explanation: "Revalidation policies trade freshness against caching benefits.",
    illustration: {
      kind: "svg",
      diagram: "cache-layers",
      alt: "Cache layers with freshness concerns",
      caption: "Revalidate = freshness policy",
    },
  },
  {
    id: 358,
    type: "boolean",
    topic: "nextjs",
    difficulty: "medium",
    prompt: "Every App Router page is always fully static at build time.",
    correct: false,
    explanation: "Routes can be static, dynamic, or mixed depending on data and APIs used.",
  },
  {
    id: 359,
    type: "single",
    topic: "nextjs",
    difficulty: "hard",
    prompt: "Shipping a database password in NEXT_PUBLIC_DATABASE_URL is:",
    options: [
      { id: "d", label: "Ignored by all browsers" },
      { id: "a", label: "Dangerous — it can leak to anyone who loads the client bundle" },
      { id: "b", label: "Required by Next.js" },
      { id: "c", label: "The only way to call fetch" },
    ],
    correctId: "a",
    explanation: "Public env vars are public. Keep secrets on the server.",
  },
  {
    id: 360,
    type: "single",
    topic: "nextjs",
    difficulty: "medium",
    prompt: "Edge middleware is usually the best place for which kind of work?",
    options: [
      { id: "a", label: "Lightweight auth redirects, headers, and A/B routing" },
      { id: "b", label: "Multi-minute machine-learning training jobs" },
      { id: "c", label: "Direct low-level disk formatting" },
      { id: "d", label: "Replacing your entire database with CSS" },
    ],
    correctId: "a",
    explanation: "Keep middleware fast and simple; heavy work belongs in server routes/jobs.",
    illustration: {
      kind: "svg",
      diagram: "request-path",
      alt: "Edge hop before the application",
      caption: "Edge work should stay light",
    },
  },
  {
    id: 361,
    type: "fill",
    topic: "nextjs",
    difficulty: "easy",
    prompt: "What directive string marks a Client Component file? (two words, quoted form optional)",
    accept: ["use client", '"use client"', "'use client'"],
    placeholder: "use ...",
    explanation: 'Put "use client" at the top of modules that need client-only APIs.',
  },
  {
    id: 362,
    type: "single",
    topic: "nextjs",
    difficulty: "hard",
    prompt: "Where does a fetch inside a Server Component run?",
    options: [
      { id: "c", label: "Inside the CSS cascade" },
      { id: "d", label: "In the DNS registrar UI" },
      { id: "a", label: "On the server during render" },
      { id: "b", label: "Only on the visitor's smartwatch" },
    ],
    correctId: "a",
    explanation: "Server Components execute on the server, so fetch there stays off the client.",
    illustration: {
      kind: "svg",
      diagram: "nextjs-layers",
      alt: "Server layer talking to the data layer",
      caption: "Server Component fetch hits data on the server",
    },
  },
  {
    id: 363,
    type: "multi",
    topic: "nextjs",
    difficulty: "medium",
    prompt: "Which are plausible Next.js production deployment shapes? (select all)",
    options: [
      { id: "a", label: "Node.js server" },
      { id: "b", label: "Serverless functions" },
      { id: "c", label: "Edge runtime for some routes" },
      { id: "d", label: "Only via FTP upload of node_modules to a toaster" },
    ],
    correctIds: ["a", "b", "c"],
    explanation: "Real hosts use Node, serverless, and/or edge — not appliance jokes.",
  },
  {
    id: 364,
    type: "boolean",
    topic: "nextjs",
    difficulty: "easy",
    prompt: "Route Handlers can serve as a small HTTP API inside a Next.js app.",
    correct: true,
    explanation: "Many apps expose JSON APIs via route handlers instead of a separate Express server.",
  },
];
