import type { QuizQuestion } from "../types.ts";

export const nodejsQuestions: QuizQuestion[] = [
  {
    id: 151,
    type: "single",
    topic: "nodejs",
    difficulty: "easy",
    prompt: "What is Node.js primarily?",
    options: [
      { id: "a", label: "A browser-only JavaScript framework" },
      { id: "b", label: "A JavaScript runtime built on V8 for server/side tooling" },
      { id: "c", label: "A SQL database" },
      { id: "d", label: "A CSS preprocessor" },
    ],
    correctId: "b",
    explanation: "Node runs JS outside the browser using V8 plus libuv for async I/O.",
  },
  {
    id: 152,
    type: "single",
    topic: "nodejs",
    difficulty: "easy",
    prompt: "Which object provides the command-line arguments in a Node process?",
    options: [
      { id: "a", label: "process.argv" },
      { id: "b", label: "window.args" },
      { id: "c", label: "global.params" },
      { id: "d", label: "os.argv" },
    ],
    correctId: "a",
    explanation: "`process.argv` is an array: node path, script path, then user args.",
  },
  {
    id: 153,
    type: "single",
    topic: "nodejs",
    difficulty: "medium",
    prompt: "What does `require` load in CommonJS?",
    options: [
      { id: "a", label: "Only JSON files" },
      { id: "b", label: "Modules (files/packages) exported via module.exports / exports" },
      { id: "c", label: "CSS modules only" },
      { id: "d", label: "Browser globals automatically" },
    ],
    correctId: "b",
    explanation: "CommonJS `require` loads modules; ESM uses `import`.",
  },
  {
    id: 154,
    type: "single",
    topic: "nodejs",
    difficulty: "medium",
    prompt: "Which core module is used to create an HTTP server without Express?",
    options: [
      { id: "a", label: "fs" },
      { id: "b", label: "http" },
      { id: "c", label: "path" },
      { id: "d", label: "url only" },
    ],
    correctId: "b",
    explanation: "`http.createServer` (or `http2`/`https`) handles HTTP networking.",
  },
  {
    id: 155,
    type: "single",
    topic: "nodejs",
    difficulty: "hard",
    prompt: "What is the Event Loop's role in Node?",
    options: [
      { id: "a", label: "Compile TypeScript to JavaScript" },
      { id: "b", label: "Coordinate async callbacks/I/O completion on a single JS thread" },
      { id: "c", label: "Manage SQL transactions only" },
      { id: "d", label: "Replace V8 entirely" },
    ],
    correctId: "b",
    explanation: "JS runs on one thread; the event loop schedules callbacks when async work completes.",
  },
  {
    id: 156,
    type: "multi",
    topic: "nodejs",
    difficulty: "easy",
    prompt: "Which are Node.js core modules? (select all)",
    options: [
      { id: "a", label: "fs" },
      { id: "b", label: "path" },
      { id: "c", label: "jquery" },
      { id: "d", label: "events" },
    ],
    correctIds: ["a", "b", "d"],
    explanation: "`jquery` is a browser library, not a Node core module.",
  },
  {
    id: 157,
    type: "multi",
    topic: "nodejs",
    difficulty: "medium",
    prompt: "Which statements about `package.json` are true? (select all)",
    options: [
      { id: "a", label: "It lists package metadata and dependencies" },
      { id: "b", label: "scripts can define npm run commands" },
      { id: "c", label: "It replaces the need for node_modules entirely" },
      { id: "d", label: "\"type\": \"module\" enables ESM syntax by default for .js files" },
    ],
    correctIds: ["a", "b", "d"],
    explanation: "Dependencies still install into node_modules (or equivalent); package.json declares them.",
  },
  {
    id: 158,
    type: "multi",
    topic: "nodejs",
    difficulty: "medium",
    prompt: "Which are appropriate for reading environment configuration? (select all)",
    options: [
      { id: "a", label: "process.env.PORT" },
      { id: "b", label: "Hardcoding production secrets in source" },
      { id: "c", label: ".env files loaded in development (not committed secrets)" },
      { id: "d", label: "Hosting provider env vars in production" },
    ],
    correctIds: ["a", "c", "d"],
    explanation: "Never commit secrets; use env vars and secret stores.",
  },
  {
    id: 159,
    type: "boolean",
    topic: "nodejs",
    difficulty: "easy",
    prompt: "Node.js can run JavaScript on the server without a web browser.",
    correct: true,
    explanation: "That is the core value proposition of Node.",
  },
  {
    id: 160,
    type: "boolean",
    topic: "nodejs",
    difficulty: "medium",
    prompt: "`fs.readFileSync` is non-blocking and never stalls the event loop.",
    correct: false,
    explanation: "Sync fs methods block the event loop; prefer async `fs.promises` / callbacks for servers.",
  },
  {
    id: 161,
    type: "boolean",
    topic: "nodejs",
    difficulty: "easy",
    prompt: "`npm install` reads package.json / lockfile to install dependencies.",
    correct: true,
    explanation: "npm (or pnpm/yarn) installs deps listed in the package manifests.",
  },
  {
    id: 162,
    type: "fill",
    topic: "nodejs",
    difficulty: "easy",
    prompt: "What global object is used to exit the process with a status code, e.g. `____.exit(1)`?",
    accept: ["process"],
    placeholder: "process",
    explanation: "`process.exit(code)` terminates the Node process.",
  },
  {
    id: 163,
    type: "fill",
    topic: "nodejs",
    difficulty: "medium",
    prompt: "Which core module joins path segments in a cross-platform way? (`const path = require('____')`)",
    accept: ["path"],
    explanation: "`path.join` / `path.resolve` handle OS-specific separators.",
  },
  {
    id: 164,
    type: "fill",
    topic: "nodejs",
    difficulty: "medium",
    prompt: "Express (and many apps) use which HTTP method name for reading a resource by URL? (common REST verb)",
    accept: ["GET", "get"],
    placeholder: "GET",
    explanation: "GET retrieves a resource without a request body in typical REST design.",
  },
  {
    id: 165,
    type: "order",
    topic: "nodejs",
    difficulty: "medium",
    prompt: "Order the steps to handle a JSON POST body in a simple Express-style API:",
    items: [
      { id: "middleware", label: "JSON body parser middleware" },
      { id: "route", label: "Route handler reads req.body" },
      { id: "respond", label: "res.status(...).json(...)" },
    ],
    correctOrder: ["middleware", "route", "respond"],
    explanation: "Parse body first, then handle the route, then send a response.",
  },
  {
    id: 166,
    type: "order",
    topic: "nodejs",
    difficulty: "easy",
    prompt: "Order a typical project bootstrap:",
    items: [
      { id: "init", label: "npm init / create package.json" },
      { id: "install", label: "install dependencies" },
      { id: "start", label: "node index.js / npm start" },
    ],
    correctOrder: ["init", "install", "start"],
    explanation: "Declare package, install deps, run the entrypoint.",
  },
  {
    id: 167,
    type: "snippet",
    topic: "nodejs",
    difficulty: "easy",
    prompt: "Which snippet correctly creates a minimal HTTP server that responds with Hello?",
    snippets: [
      {
        id: "a",
        code: `import http from "node:http";
http.createServer((req, res) => {
  res.writeHead(200, { "Content-Type": "text/plain" });
  res.end("Hello");
}).listen(3000);`,
      },
      {
        id: "b",
        code: `import http from "node:http";
http.listen(3000, () => "Hello");`,
      },
      {
        id: "c",
        code: `fetch.createServer(3000).send("Hello");`,
      },
    ],
    correctId: "a",
    explanation: "`createServer` takes a request listener; write headers and `end` the response.",
  },
  {
    id: 168,
    type: "snippet",
    topic: "nodejs",
    difficulty: "medium",
    prompt: "Which snippet correctly reads a file asynchronously with promises?",
    snippets: [
      {
        id: "a",
        code: `import { readFile } from "node:fs/promises";
const text = await readFile("notes.txt", "utf8");`,
      },
      {
        id: "b",
        code: `import fs from "node:fs";
const text = fs.readFileSync("notes.txt");
// always preferred on servers`,
      },
      {
        id: "c",
        code: `const text = require("notes.txt");`,
      },
    ],
    correctId: "a",
    explanation: "`fs/promises` provides promise-based async file APIs suitable for async/await.",
  },
  {
    id: 169,
    type: "match",
    topic: "nodejs",
    difficulty: "easy",
    prompt: "Match each module/API to its use.",
    left: [
      { id: "fs", label: "fs" },
      { id: "path", label: "path" },
      { id: "http", label: "http" },
      { id: "url", label: "url" },
    ],
    right: [
      { id: "r1", label: "filesystem read/write" },
      { id: "r2", label: "path manipulation" },
      { id: "r3", label: "HTTP server/client primitives" },
      { id: "r4", label: "parse and construct URLs" },
    ],
    pairs: { fs: "r1", path: "r2", http: "r3", url: "r4" },
  },
  {
    id: 170,
    type: "match",
    topic: "nodejs",
    difficulty: "medium",
    prompt: "Match each HTTP status code to a typical meaning.",
    left: [
      { id: "s200", label: "200" },
      { id: "s201", label: "201" },
      { id: "s400", label: "400" },
      { id: "s404", label: "404" },
      { id: "s500", label: "500" },
    ],
    right: [
      { id: "r1", label: "OK" },
      { id: "r2", label: "Created" },
      { id: "r3", label: "Bad Request" },
      { id: "r4", label: "Not Found" },
      { id: "r5", label: "Internal Server Error" },
    ],
    pairs: { s200: "r1", s201: "r2", s400: "r3", s404: "r4", s500: "r5" },
  },
  {
    id: 171,
    type: "hotspot",
    topic: "nodejs",
    difficulty: "medium",
    prompt: "Click the line that blocks the event loop during a request handler.",
    code: `server.on("request", (req, res) => {
  const data = fs.readFileSync("./big.json", "utf8");
  res.end(data);
});
console.log("listening");`,
    regions: [
      { id: "r1", label: "Line 1: request handler start", startLine: 1, endLine: 1 },
      { id: "r2", label: "Line 2: readFileSync", startLine: 2, endLine: 2 },
      { id: "r3", label: "Line 3: res.end", startLine: 3, endLine: 3 },
      { id: "r4", label: "Line 5: console.log", startLine: 5, endLine: 5 },
    ],
    correctRegionId: "r2",
    explanation: "Synchronous file I/O blocks other requests on the main thread.",
  },
  {
    id: 172,
    type: "hotspot",
    topic: "nodejs",
    difficulty: "hard",
    prompt: "Click the line that leaks a secret if this file is committed to git.",
    code: `import express from "express";
const app = express();
const API_KEY = "sk_live_example_secret_key";
app.get("/health", (req, res) => res.send("ok"));`,
    regions: [
      { id: "r1", label: "Line 1: import", startLine: 1, endLine: 1 },
      { id: "r2", label: "Line 2: express app", startLine: 2, endLine: 2 },
      { id: "r3", label: "Line 3: hardcoded API key", startLine: 3, endLine: 3 },
      { id: "r4", label: "Line 4: health route", startLine: 4, endLine: 4 },
    ],
    correctRegionId: "r3",
    explanation: "Secrets belong in environment variables or a secret manager, not source control.",
  },
  {
    id: 173,
    type: "output",
    topic: "nodejs",
    difficulty: "easy",
    prompt: "What is logged?",
    code: `console.log(process.argv[0] ? "has-node-path" : "missing");`,
    accept: ["has-node-path"],
    explanation: "`process.argv[0]` is the node executable path and is always present.",
  },
  {
    id: 174,
    type: "output",
    topic: "nodejs",
    difficulty: "medium",
    prompt: "What is printed?",
    code: `import path from "node:path";
console.log(path.join("a", "b", "c.txt"));`,
    accept: ["a/b/c.txt", "a\\b\\c.txt"],
    explanation: "`path.join` joins with the platform separator (`/` on Unix, `\\` on Windows).",
  },
  {
    id: 175,
    type: "single",
    topic: "nodejs",
    difficulty: "hard",
    prompt: "What is middleware in Express?",
    options: [
      { id: "a", label: "A function (req, res, next) that runs in the request pipeline" },
      { id: "b", label: "A SQL table for sessions only" },
      { id: "c", label: "The V8 garbage collector" },
      { id: "d", label: "A replacement for package.json" },
    ],
    correctId: "a",
    explanation: "Middleware composes cross-cutting concerns: logging, auth, parsers, errors, etc.",
  },
];
