import type { QuizQuestion } from "../types.ts";

export const postgresqlQuestions: QuizQuestion[] = [
  {
    id: 211,
    type: "single",
    topic: "postgresql",
    difficulty: "easy",
    prompt: "Which clause filters rows before grouping?",
    options: [
      { id: "a", label: "WHERE" },
      { id: "b", label: "HAVING" },
      { id: "c", label: "LIMIT" },
      { id: "d", label: "OFFSET" },
    ],
    correctId: "a",
    explanation: "WHERE filters rows; HAVING filters groups after GROUP BY.",
  },
  {
    id: 212,
    type: "single",
    topic: "postgresql",
    difficulty: "easy",
    prompt: "Which clause sorts query results?",
    options: [
      { id: "a", label: "GROUP BY" },
      { id: "b", label: "ORDER BY" },
      { id: "c", label: "RETURNING" },
      { id: "d", label: "VALUES" },
    ],
    correctId: "b",
    explanation: "ORDER BY sorts rows, optionally with ASC or DESC for each expression.",
  },
  {
    id: 213,
    type: "single",
    topic: "postgresql",
    difficulty: "medium",
    prompt: "What does an INNER JOIN return?",
    options: [
      { id: "a", label: "Every row from the left table, with optional right-side data" },
      { id: "b", label: "Only rows with matching join values in both tables" },
      { id: "c", label: "A Cartesian product regardless of the join condition" },
      { id: "d", label: "Only rows whose joined columns are NULL" },
    ],
    correctId: "b",
    explanation: "An INNER JOIN excludes rows that have no match under its join condition.",
  },
  {
    id: 214,
    type: "single",
    topic: "postgresql",
    difficulty: "medium",
    prompt: "What is the primary purpose of a primary key?",
    options: [
      { id: "a", label: "To uniquely identify each table row" },
      { id: "b", label: "To automatically encrypt a column" },
      { id: "c", label: "To allow duplicate values for faster inserts" },
      { id: "d", label: "To sort all SELECT results by default" },
    ],
    correctId: "a",
    explanation: "A primary key is unique and NOT NULL, so it identifies a row.",
  },
  {
    id: 215,
    type: "single",
    topic: "postgresql",
    difficulty: "medium",
    prompt: "Why would you add an index to a column often used in selective WHERE clauses?",
    options: [
      { id: "a", label: "To guarantee the query output order" },
      { id: "b", label: "To help PostgreSQL locate matching rows without scanning every row" },
      { id: "c", label: "To prevent all duplicate values" },
      { id: "d", label: "To automatically create a foreign key" },
    ],
    correctId: "b",
    explanation: "Indexes can speed qualifying lookups, though they also cost storage and write work.",
  },
  {
    id: 216,
    type: "single",
    topic: "postgresql",
    difficulty: "medium",
    prompt: "Which operator performs case-insensitive pattern matching in PostgreSQL?",
    options: [
      { id: "a", label: "LIKE" },
      { id: "b", label: "ILIKE" },
      { id: "c", label: "IN" },
      { id: "d", label: "IS" },
    ],
    correctId: "b",
    explanation: "ILIKE is PostgreSQL's case-insensitive counterpart to LIKE.",
  },
  {
    id: 217,
    type: "multi",
    topic: "postgresql",
    difficulty: "medium",
    prompt: "Which statements about NULL are true? (select all)",
    options: [
      { id: "a", label: "Use IS NULL to test whether a value is NULL" },
      { id: "b", label: "NULL = NULL evaluates to true" },
      { id: "c", label: "A WHERE condition that evaluates to unknown does not keep the row" },
      { id: "d", label: "NULL means the same thing as an empty string in every type" },
    ],
    correctIds: ["a", "c"],
    explanation: "NULL represents unknown or absent data; comparisons with it are unknown, not true.",
  },
  {
    id: 218,
    type: "multi",
    topic: "postgresql",
    difficulty: "medium",
    prompt: "Which features can enforce relationships between tables? (select all)",
    options: [
      { id: "a", label: "A FOREIGN KEY constraint" },
      { id: "b", label: "A primary or unique key referenced by the foreign key" },
      { id: "c", label: "An ORDER BY clause" },
      { id: "d", label: "ON DELETE rules such as CASCADE or RESTRICT" },
    ],
    correctIds: ["a", "b", "d"],
    explanation: "Foreign keys reference a unique key and can define behavior when referenced rows change.",
  },
  {
    id: 219,
    type: "multi",
    topic: "postgresql",
    difficulty: "hard",
    prompt: "Which statements about JSONB operators are true? (select all)",
    options: [
      { id: "a", label: "`data -> 'name'` returns JSON/JSONB" },
      { id: "b", label: "`data ->> 'name'` returns text" },
      { id: "c", label: "`->>` is the operator for updating a JSONB key" },
      { id: "d", label: "Both operators can access an object field by key" },
    ],
    correctIds: ["a", "b", "d"],
    explanation: "`->` keeps the JSON value; `->>` extracts its text representation.",
  },
  {
    id: 220,
    type: "boolean",
    topic: "postgresql",
    difficulty: "easy",
    prompt: "`LIMIT 10` restricts a query result to at most ten rows.",
    correct: true,
    explanation: "LIMIT caps the number of rows returned after ordering.",
  },
  {
    id: 221,
    type: "boolean",
    topic: "postgresql",
    difficulty: "medium",
    prompt: "`COUNT(column_name)` counts NULL values in that column.",
    correct: false,
    explanation: "COUNT(column_name) counts only non-NULL values; COUNT(*) counts rows.",
  },
  {
    id: 222,
    type: "boolean",
    topic: "postgresql",
    difficulty: "medium",
    prompt: "Changes made after BEGIN become permanent only when COMMIT succeeds.",
    correct: true,
    explanation: "COMMIT makes the transaction's changes durable; ROLLBACK discards them.",
  },
  {
    id: 223,
    type: "fill",
    topic: "postgresql",
    difficulty: "easy",
    prompt: "Complete the query to return only rows where `active` is true: `SELECT * FROM users ____ active = true;`",
    accept: ["WHERE", "where"],
    placeholder: "WHERE",
    explanation: "WHERE filters individual rows before any grouping.",
  },
  {
    id: 224,
    type: "fill",
    topic: "postgresql",
    difficulty: "medium",
    prompt: "Which command ends a transaction and keeps its changes? `____;`",
    accept: ["COMMIT", "commit"],
    placeholder: "COMMIT",
    explanation: "COMMIT persists the transaction's completed work.",
  },
  {
    id: 225,
    type: "fill",
    topic: "postgresql",
    difficulty: "medium",
    prompt: "Add the clause that returns inserted columns: `INSERT INTO users (email) VALUES ('a@example.com') ____ id;`",
    accept: ["RETURNING", "returning"],
    placeholder: "RETURNING",
    explanation: "RETURNING lets INSERT, UPDATE, or DELETE return values from affected rows.",
  },
  {
    id: 226,
    type: "order",
    topic: "postgresql",
    difficulty: "medium",
    prompt: "Order these common clauses in a SELECT query:",
    items: [
      { id: "select", label: "SELECT columns" },
      { id: "from", label: "FROM table" },
      { id: "where", label: "WHERE condition" },
      { id: "order", label: "ORDER BY column" },
      { id: "limit", label: "LIMIT count" },
    ],
    correctOrder: ["select", "from", "where", "order", "limit"],
    explanation: "This is the usual SQL clause order for a basic filtered, sorted, limited query.",
  },
  {
    id: 227,
    type: "order",
    topic: "postgresql",
    difficulty: "medium",
    prompt: "Order a successful transaction that creates an account and a profile:",
    items: [
      { id: "begin", label: "BEGIN" },
      { id: "account", label: "INSERT the account" },
      { id: "profile", label: "INSERT the related profile" },
      { id: "commit", label: "COMMIT" },
    ],
    correctOrder: ["begin", "account", "profile", "commit"],
    explanation: "The work is grouped between BEGIN and COMMIT so it succeeds or rolls back together.",
  },
  {
    id: 228,
    type: "snippet",
    topic: "postgresql",
    difficulty: "easy",
    prompt: "Which query correctly returns the five newest posts?",
    snippets: [
      {
        id: "a",
        code: `SELECT *
FROM posts
ORDER BY created_at DESC
LIMIT 5;`,
      },
      {
        id: "b",
        code: `SELECT *
FROM posts
LIMIT 5
ORDER BY created_at DESC;`,
      },
      {
        id: "c",
        code: `SELECT newest(5)
FROM posts;`,
      },
    ],
    correctId: "a",
    explanation: "Sort by created_at descending, then limit the sorted rows to five.",
  },
  {
    id: 229,
    type: "snippet",
    topic: "postgresql",
    difficulty: "hard",
    prompt: "Which query counts orders for each customer?",
    snippets: [
      {
        id: "a",
        code: `SELECT customer_id, COUNT(*) AS order_count
FROM orders
GROUP BY customer_id;`,
      },
      {
        id: "b",
        code: `SELECT customer_id, COUNT(*)
FROM orders;`,
      },
      {
        id: "c",
        code: `SELECT GROUP BY customer_id, COUNT(*)
FROM orders;`,
      },
    ],
    correctId: "a",
    explanation: "Every selected non-aggregate column must be grouped when aggregating in this way.",
  },
  {
    id: 230,
    type: "match",
    topic: "postgresql",
    difficulty: "easy",
    prompt: "Match each SQL term to its role.",
    left: [
      { id: "pk", label: "PRIMARY KEY" },
      { id: "fk", label: "FOREIGN KEY" },
      { id: "index", label: "INDEX" },
      { id: "returning", label: "RETURNING" },
    ],
    right: [
      { id: "r1", label: "uniquely identifies a row" },
      { id: "r2", label: "references a key in another table" },
      { id: "r3", label: "can speed qualifying lookups" },
      { id: "r4", label: "returns affected-row values from a write" },
    ],
    pairs: { pk: "r1", fk: "r2", index: "r3", returning: "r4" },
  },
  {
    id: 231,
    type: "match",
    topic: "postgresql",
    difficulty: "medium",
    prompt: "Match each aggregate expression to what it counts.",
    left: [
      { id: "all", label: "COUNT(*)" },
      { id: "email", label: "COUNT(email)" },
      { id: "distinct", label: "COUNT(DISTINCT email)" },
    ],
    right: [
      { id: "r1", label: "all rows, including rows with NULL email" },
      { id: "r2", label: "rows whose email is not NULL" },
      { id: "r3", label: "distinct non-NULL email values" },
    ],
    pairs: { all: "r1", email: "r2", distinct: "r3" },
  },
  {
    id: 232,
    type: "hotspot",
    topic: "postgresql",
    difficulty: "medium",
    prompt: "Click the line that correctly filters rows with no manager.",
    code: `SELECT id, name
FROM employees
WHERE manager_id IS NULL
ORDER BY name;`,
    regions: [
      { id: "r1", label: "Line 1: selected columns", startLine: 1, endLine: 1 },
      { id: "r2", label: "Line 2: source table", startLine: 2, endLine: 2 },
      { id: "r3", label: "Line 3: NULL filter", startLine: 3, endLine: 3 },
      { id: "r4", label: "Line 4: sorting", startLine: 4, endLine: 4 },
    ],
    correctRegionId: "r3",
    explanation: "NULL must be tested with IS NULL rather than = NULL.",
  },
  {
    id: 233,
    type: "hotspot",
    topic: "postgresql",
    difficulty: "hard",
    prompt: "Click the line that extracts the JSONB `name` field as text.",
    code: `SELECT
  profile -> 'name' AS name_json,
  profile ->> 'name' AS name_text
FROM users;`,
    regions: [
      { id: "r1", label: "Line 1: SELECT", startLine: 1, endLine: 1 },
      { id: "r2", label: "Line 2: JSON value extraction", startLine: 2, endLine: 2 },
      { id: "r3", label: "Line 3: text extraction", startLine: 3, endLine: 3 },
      { id: "r4", label: "Line 4: source table", startLine: 4, endLine: 4 },
    ],
    correctRegionId: "r3",
    explanation: "`->>` extracts a JSONB field as text, while `->` returns a JSONB value.",
  },
  {
    id: 234,
    type: "output",
    topic: "postgresql",
    difficulty: "easy",
    prompt: "What value does this query return?",
    code: `SELECT COUNT(*)
FROM (VALUES (1), (2), (3)) AS numbers(n);`,
    accept: ["3"],
    explanation: "COUNT(*) counts every row in the three-row VALUES result.",
  },
  {
    id: 235,
    type: "output",
    topic: "postgresql",
    difficulty: "medium",
    prompt: "What text does this query return?",
    code: `SELECT '{"name":"Ada"}'::jsonb ->> 'name';`,
    accept: ["Ada", "ada"],
    explanation: "The `->>` operator extracts the JSONB field as text.",
  },
];
