import type { QuizQuestion } from "../types.ts";

export const pythonQuestions: QuizQuestion[] = [
  {
    id: 271, type: "single", topic: "python", difficulty: "easy",
    prompt: "Which built-in type is immutable?",
    options: [{ id: "a", label: "list" }, { id: "b", label: "dict" }, { id: "c", label: "tuple" }, { id: "d", label: "set" }],
    correctId: "c",
    explanation: "Tuples are immutable; lists, dictionaries, and sets can be changed after creation.",
  },
  {
    id: 272, type: "single", topic: "python", difficulty: "easy",
    prompt: "Which value means “no value” in Python?",
    options: [{ id: "a", label: "False" }, { id: "b", label: "0" }, { id: "c", label: '""' }, { id: "d", label: "None" }],
    correctId: "d",
    explanation: "`None` is Python's singleton value for an intentional absence of a value. It is falsy, but it is not the same as `False` or `0`.",
  },
  {
    id: 273, type: "single", topic: "python", difficulty: "medium",
    prompt: "Which expression compares whether two variables refer to the same object?",
    options: [{ id: "a", label: "a == b" }, { id: "b", label: "a is b" }, { id: "c", label: "a equals b" }, { id: "d", label: "same(a, b)" }],
    correctId: "b",
    explanation: "`is` checks object identity. `==` checks whether values compare equal.",
  },
  {
    id: 274, type: "single", topic: "python", difficulty: "easy",
    prompt: "Which collection stores key-value pairs?",
    options: [{ id: "a", label: "list" }, { id: "b", label: "tuple" }, { id: "c", label: "dict" }, { id: "d", label: "set" }],
    correctId: "c",
    explanation: "A dictionary maps unique keys to values, such as `{'name': 'Ada'}`.",
  },
  {
    id: 275, type: "single", topic: "python", difficulty: "medium",
    prompt: "What does `items[1:4]` return for a list?",
    options: [{ id: "a", label: "Items at indexes 1 through 4, inclusive" }, { id: "b", label: "Items at indexes 1, 2, and 3" }, { id: "c", label: "Only the item at index 4" }, { id: "d", label: "A syntax error" }],
    correctId: "b",
    explanation: "A slice includes its start index and stops before its end index.",
  },
  {
    id: 276, type: "single", topic: "python", difficulty: "medium",
    prompt: "Why is `def add(item, items=[]): ...` usually risky?",
    options: [{ id: "a", label: "Lists cannot be function arguments" }, { id: "b", label: "The same default list is reused across calls" }, { id: "c", label: "Python copies the list too often" }, { id: "d", label: "Default arguments must be tuples" }],
    correctId: "b",
    explanation: "Default argument expressions are evaluated once when the function is defined. Mutating that list affects later calls.",
  },
  {
    id: 277, type: "single", topic: "python", difficulty: "easy",
    prompt: "What does `enumerate(names)` provide while looping?",
    options: [{ id: "a", label: "Only each name" }, { id: "b", label: "An index and each name" }, { id: "c", label: "Sorted names" }, { id: "d", label: "A dictionary" }],
    correctId: "b",
    explanation: "`enumerate` yields `(index, value)` pairs, so you can loop with `for index, name in enumerate(names):`.",
  },
  {
    id: 278, type: "single", topic: "python", difficulty: "medium",
    prompt: "Which call sorts users by their `age` key without changing the original list?",
    options: [{ id: "a", label: "users.sort(key=lambda user: user['age'])" }, { id: "b", label: "sorted(users, key=lambda user: user['age'])" }, { id: "c", label: "users.sorted('age')" }, { id: "d", label: "sort(users.age)" }],
    correctId: "b",
    explanation: "`sorted` returns a new list. `list.sort` changes the original list in place.",
  },
  {
    id: 279, type: "single", topic: "python", difficulty: "easy",
    prompt: "Which string method removes whitespace from both ends of a string?",
    options: [{ id: "a", label: "trim()" }, { id: "b", label: "strip()" }, { id: "c", label: "clean()" }, { id: "d", label: "remove()" }],
    correctId: "b",
    explanation: "`strip()` removes leading and trailing whitespace by default.",
  },
  {
    id: 280, type: "single", topic: "python", difficulty: "medium",
    prompt: "For repeated membership checks in a large collection of unique values, which is usually the better fit?",
    options: [{ id: "a", label: "list" }, { id: "b", label: "set" }, { id: "c", label: "tuple" }, { id: "d", label: "string" }],
    correctId: "b",
    explanation: "Set membership is usually average O(1), while checking a list usually scans items one by one.",
  },
  {
    id: 281, type: "multi", topic: "python", difficulty: "easy",
    prompt: "Which values are falsy in Python? (select all)",
    options: [{ id: "a", label: "0" }, { id: "b", label: '""' }, { id: "c", label: "[]" }, { id: "d", label: "{}" }, { id: "e", label: "None" }, { id: "f", label: "[0]" }],
    correctIds: ["a", "b", "c", "d", "e"],
    explanation: "Zero, empty collections/strings, and `None` are falsy. A non-empty list is truthy even if it contains `0`.",
  },
  {
    id: 282, type: "multi", topic: "python", difficulty: "medium",
    prompt: "Which statements about function parameters are true? (select all)",
    options: [{ id: "a", label: "`*args` collects extra positional arguments into a tuple" }, { id: "b", label: "`**kwargs` collects extra keyword arguments into a dictionary" }, { id: "c", label: "`*args` can only contain integers" }, { id: "d", label: "`**kwargs` lets callers pass named extra arguments" }],
    correctIds: ["a", "b", "d"],
    explanation: "`*args` and `**kwargs` collect extra arguments; they do not restrict the types of supplied values.",
  },
  {
    id: 283, type: "multi", topic: "python", difficulty: "medium",
    prompt: "Which are common ways to handle an expected exception? (select all)",
    options: [{ id: "a", label: "Wrap the risky code in `try` / `except`" }, { id: "b", label: "Catch a specific exception such as `ValueError`" }, { id: "c", label: "Use `finally` for cleanup that should run either way" }, { id: "d", label: "Ignore all errors with a bare `except` in production" }],
    correctIds: ["a", "b", "c"],
    explanation: "Handle exceptions as narrowly as practical. `finally` runs whether or not an exception is raised; broad catches can hide real problems.",
  },
  {
    id: 284, type: "multi", topic: "python", difficulty: "medium",
    prompt: "Which statements about imports are correct? (select all)",
    options: [{ id: "a", label: "`import math` uses names such as `math.sqrt(9)`" }, { id: "b", label: "`from math import sqrt` lets you call `sqrt(9)`" }, { id: "c", label: "`from math import *` is usually clearer in application code" }, { id: "d", label: "Imports normally run a module's top-level code once per process" }],
    correctIds: ["a", "b", "d"],
    explanation: "Both import styles shown are valid. Wildcard imports obscure where names came from, so avoid them in normal application code.",
  },
  {
    id: 285, type: "boolean", topic: "python", difficulty: "easy",
    prompt: "`None == False` evaluates to `True` in Python.",
    correct: false,
    explanation: "Both values are falsy in a boolean context, but they are different values, so `None == False` is false.",
  },
  {
    id: 286, type: "boolean", topic: "python", difficulty: "easy",
    prompt: "A `with open(...) as file:` block closes the file when the block exits, even if an exception occurs.",
    correct: true,
    explanation: "The context manager handles cleanup when leaving the `with` block.",
  },
  {
    id: 287, type: "boolean", topic: "python", difficulty: "medium",
    prompt: "Looking up a value by key in a dictionary is usually faster than scanning a list for a matching value.",
    correct: true,
    explanation: "Dictionary key lookup is usually average O(1); finding a match in a list is usually O(n).",
  },
  {
    id: 288, type: "fill", topic: "python", difficulty: "easy",
    prompt: "Complete the f-string: `message = f\"Hello, {____}!\"`",
    accept: ["name"],
    placeholder: "variable name",
    explanation: "An f-string evaluates expressions inside braces, such as `{name}`.",
  },
  {
    id: 289, type: "fill", topic: "python", difficulty: "easy",
    prompt: "Complete: `for left, right in ____([1, 2], ['a', 'b']):`",
    accept: ["zip"],
    placeholder: "function name",
    explanation: "`zip` combines corresponding items from iterables into pairs.",
  },
  {
    id: 290, type: "fill", topic: "python", difficulty: "medium",
    prompt: "Complete the safe mutable-default pattern: `def add(item, items=____):`",
    accept: ["None", "none"],
    placeholder: "value",
    explanation: "Use `None`, then create a new list inside the function when needed.",
  },
  {
    id: 291, type: "fill", topic: "python", difficulty: "easy",
    prompt: "In an instance method, the conventional first parameter is named `____`.",
    accept: ["self"],
    placeholder: "parameter name",
    explanation: "`self` refers to the instance on which the method was called.",
  },
  {
    id: 292, type: "order", topic: "python", difficulty: "easy",
    prompt: "Order the usual steps for reading a text file safely:",
    items: [{ id: "with", label: "Open it with a `with` block" }, { id: "read", label: "Read or iterate over its contents" }, { id: "exit", label: "Leave the block so it is closed" }],
    correctOrder: ["with", "read", "exit"],
    explanation: "Open the file through its context manager, use it in the block, then let the context manager close it.",
  },
  {
    id: 293, type: "order", topic: "python", difficulty: "medium",
    prompt: "Order these parts of a targeted exception flow:",
    items: [{ id: "try", label: "Run the risky operation in `try`" }, { id: "except", label: "Handle the expected exception in `except`" }, { id: "finally", label: "Run cleanup in `finally` when needed" }],
    correctOrder: ["try", "except", "finally"],
    explanation: "The `try` runs first. An `except` handles a matching error, and `finally` runs afterward whether or not an error occurred.",
  },
  {
    id: 294, type: "snippet", topic: "python", difficulty: "easy",
    prompt: "Which snippet builds a list of squares for the even numbers in `numbers`?",
    snippets: [
      { id: "a", code: "[number * number for number in numbers if number % 2 == 0]" },
      { id: "b", code: "[number for number * number in numbers if even]" },
      { id: "c", code: "{number * number if number % 2 == 0 for number in numbers}" },
    ],
    correctId: "a",
    explanation: "A list comprehension has an expression, a `for` clause, and an optional filtering `if` clause.",
  },
  {
    id: 295, type: "snippet", topic: "python", difficulty: "medium",
    prompt: "Which snippet correctly appends to a new list on every call when the caller leaves `items` out?",
    snippets: [
      { id: "a", code: `def add(item, items=[]):\n    items.append(item)\n    return items` },
      { id: "b", code: `def add(item, items=None):\n    if items is None:\n        items = []\n    items.append(item)\n    return items` },
      { id: "c", code: `def add(item, items={}):\n    return items + [item]` },
    ],
    correctId: "b",
    explanation: "Using `None` as the sentinel creates a fresh list for calls that omit the argument.",
  },
  {
    id: 296, type: "snippet", topic: "python", difficulty: "medium",
    prompt: "Which snippet returns a dictionary counting each word in `words`?",
    snippets: [
      { id: "a", code: `counts = {}\nfor word in words:\n    counts[word] = counts.get(word, 0) + 1` },
      { id: "b", code: `counts = []\nfor word in words:\n    counts[word] += 1` },
      { id: "c", code: `counts = {}\nfor word in words:\n    counts.append(word)` },
    ],
    correctId: "a",
    explanation: "`dict.get(word, 0)` supplies zero for a new key, making this a common counting idiom.",
  },
  {
    id: 297, type: "match", topic: "python", difficulty: "easy",
    prompt: "Match each collection to its main characteristic.",
    left: [{ id: "list", label: "list" }, { id: "tuple", label: "tuple" }, { id: "dict", label: "dict" }, { id: "set", label: "set" }],
    right: [{ id: "r1", label: "ordered and mutable sequence" }, { id: "r2", label: "ordered and immutable sequence" }, { id: "r3", label: "key-value mapping" }, { id: "r4", label: "unique values with fast membership checks" }],
    pairs: { list: "r1", tuple: "r2", dict: "r3", set: "r4" },
  },
  {
    id: 298, type: "match", topic: "python", difficulty: "medium",
    prompt: "Match each tool to its usual loop use.",
    left: [{ id: "range", label: "range" }, { id: "enumerate", label: "enumerate" }, { id: "zip", label: "zip" }, { id: "items", label: "dict.items()" }],
    right: [{ id: "r1", label: "generate a sequence of integer positions" }, { id: "r2", label: "pair an index with each value" }, { id: "r3", label: "combine corresponding values from iterables" }, { id: "r4", label: "iterate over dictionary key-value pairs" }],
    pairs: { range: "r1", enumerate: "r2", zip: "r3", items: "r4" },
  },
  {
    id: 299, type: "hotspot", topic: "python", difficulty: "medium",
    prompt: "Click the line that raises a `KeyError` when `user` has no `email` key.",
    code: `user = {"name": "Ada"}\nname = user["name"]\nemail = user["email"]\nprint(name)`,
    regions: [
      { id: "r1", label: "Line 1: dictionary creation", startLine: 1, endLine: 1 },
      { id: "r2", label: "Line 2: existing key lookup", startLine: 2, endLine: 2 },
      { id: "r3", label: "Line 3: missing key lookup", startLine: 3, endLine: 3 },
      { id: "r4", label: "Line 4: print", startLine: 4, endLine: 4 },
    ],
    correctRegionId: "r3",
    explanation: "Square-bracket lookup requires the key to exist. Use `user.get('email')` when a missing key should produce `None` instead.",
  },
  {
    id: 300, type: "output", topic: "python", difficulty: "medium",
    prompt: "What does this print?",
    code: `values = [1, 2, 3]\nprint(values[-1])`,
    accept: ["3"],
    explanation: "Negative indexes count from the end, so `-1` selects the last list item.",
  },
];
