import type { QuizQuestion } from "../types.ts";

export const reactQuestions: QuizQuestion[] = [
  {
    id: 91,
    type: "single",
    topic: "react",
    difficulty: "easy",
    prompt: "What does a React component typically return?",
    options: [
      { id: "a", label: "A database row" },
      { id: "b", label: "UI described as JSX / React elements" },
      { id: "c", label: "A CSS stylesheet only" },
      { id: "d", label: "Raw HTML strings that must be innerHTML'd" },
    ],
    correctId: "b",
    explanation: "Components return React elements (often written as JSX) describing the UI.",
  },
  {
    id: 92,
    type: "single",
    topic: "react",
    difficulty: "easy",
    prompt: "Which hook holds state in a function component?",
    options: [
      { id: "a", label: "useState" },
      { id: "b", label: "useHtml" },
      { id: "c", label: "useClass" },
      { id: "d", label: "useStoreOnly" },
    ],
    correctId: "a",
    explanation: "`useState` is the basic state hook for function components.",
  },
  {
    id: 93,
    type: "single",
    topic: "react",
    difficulty: "medium",
    prompt: "When does `useEffect(() => { ... }, [])` run?",
    options: [
      { id: "a", label: "On every render" },
      { id: "b", label: "Only after the initial mount (and cleanup on unmount)" },
      { id: "c", label: "Only when props change" },
      { id: "d", label: "Before the component function is defined" },
    ],
    correctId: "b",
    explanation: "An empty dependency array means mount (and cleanup on unmount).",
  },
  {
    id: 94,
    type: "single",
    topic: "react",
    difficulty: "medium",
    prompt: "What is the correct way to update state based on the previous value?",
    options: [
      { id: "a", label: "setCount(count + 1) is always safest in async flows" },
      { id: "b", label: "setCount(c => c + 1)" },
      { id: "c", label: "count++" },
      { id: "d", label: "this.count = this.count + 1" },
    ],
    correctId: "b",
    explanation: "Functional updates avoid stale closures when multiple updates batch or async delays occur.",
  },
  {
    id: 95,
    type: "single",
    topic: "react",
    difficulty: "hard",
    prompt: "Why are list keys important when rendering arrays?",
    options: [
      { id: "a", label: "They style the list items" },
      { id: "b", label: "They help React match elements across renders for reconciliation" },
      { id: "c", label: "They replace the need for state" },
      { id: "d", label: "They are only required for class components" },
    ],
    correctId: "b",
    explanation: "Stable unique keys (not index when order changes) preserve component identity and state.",
  },
  {
    id: 96,
    type: "multi",
    topic: "react",
    difficulty: "easy",
    prompt: "Which are valid React hooks? (select all)",
    options: [
      { id: "a", label: "useEffect" },
      { id: "b", label: "useMemo" },
      { id: "c", label: "useFetchAlways" },
      { id: "d", label: "useRef" },
    ],
    correctIds: ["a", "b", "d"],
    explanation: "`useFetchAlways` is not a built-in hook (you'd write a custom hook).",
  },
  {
    id: 97,
    type: "multi",
    topic: "react",
    difficulty: "medium",
    prompt: "Which are Rules of Hooks? (select all)",
    options: [
      { id: "a", label: "Only call hooks at the top level (not in loops/conditions)" },
      { id: "b", label: "Only call hooks from React functions (components or custom hooks)" },
      { id: "c", label: "Hooks may only be called inside class components" },
      { id: "d", label: "Custom hooks should start with `use`" },
    ],
    correctIds: ["a", "b", "d"],
    explanation: "Hooks are for function components and custom hooks, not classes.",
  },
  {
    id: 98,
    type: "multi",
    topic: "react",
    difficulty: "medium",
    prompt: "Which props/patterns help pass data downward? (select all)",
    options: [
      { id: "a", label: "props" },
      { id: "b", label: "Context" },
      { id: "c", label: "children" },
      { id: "d", label: "document.cookie mutation only" },
    ],
    correctIds: ["a", "b", "c"],
    explanation: "Props, context, and children composition all move data/UI through the tree.",
  },
  {
    id: 99,
    type: "boolean",
    topic: "react",
    difficulty: "easy",
    prompt: "React state updates may be asynchronous / batched; reading state immediately after setState may show the old value.",
    correct: true,
    explanation: "State updates are scheduled; use the next render or functional updates / effects as needed.",
  },
  {
    id: 100,
    type: "boolean",
    topic: "react",
    difficulty: "medium",
    prompt: "Mutating state in place (e.g. `array.push` then `setArray(array)`) is the recommended way to update arrays.",
    correct: false,
    explanation: "Treat state as immutable: copy then update (`[...arr, item]`, `map`, etc.) so React detects changes.",
  },
  {
    id: 101,
    type: "boolean",
    topic: "react",
    difficulty: "easy",
    prompt: "JSX expressions go inside curly braces, e.g. `<h1>{title}</h1>`.",
    correct: true,
    explanation: "Curly braces embed JS expressions in JSX.",
  },
  {
    id: 102,
    type: "fill",
    topic: "react",
    difficulty: "easy",
    prompt: "What prop name passes a click handler to a button in React?",
    accept: ["onClick"],
    placeholder: "onClick",
    explanation: "DOM events use camelCase in React: `onClick`, `onChange`, etc.",
  },
  {
    id: 103,
    type: "fill",
    topic: "react",
    difficulty: "medium",
    prompt: "Which hook returns a mutable ref object whose `.current` persists across renders without causing re-renders?",
    accept: ["useRef"],
    explanation: "`useRef` is for DOM nodes and mutable values that shouldn't trigger renders.",
  },
  {
    id: 104,
    type: "fill",
    topic: "react",
    difficulty: "medium",
    prompt: "Complete: `const [value, setValue] = ____(initial);`",
    accept: ["useState"],
    placeholder: "hook name",
    explanation: "`useState` returns `[state, setState]`.",
  },
  {
    id: 105,
    type: "order",
    topic: "react",
    difficulty: "medium",
    prompt: "Order a typical data-fetch effect lifecycle for a mounted component:",
    items: [
      { id: "mount", label: "Component mounts / effect runs" },
      { id: "fetch", label: "Start fetch / set loading" },
      { id: "set", label: "setState with result" },
      { id: "paint", label: "Re-render with data" },
    ],
    correctOrder: ["mount", "fetch", "set", "paint"],
    explanation: "Effects run after paint of the commit that scheduled them; then state updates re-render.",
  },
  {
    id: 106,
    type: "order",
    topic: "react",
    difficulty: "easy",
    prompt: "Order the basic steps to lift state up:",
    items: [
      { id: "identify", label: "Identify shared state needed by siblings" },
      { id: "move", label: "Move state to the closest common parent" },
      { id: "pass", label: "Pass value + setters/handlers down as props" },
    ],
    correctOrder: ["identify", "move", "pass"],
    explanation: "Lifting state keeps a single source of truth for sibling components.",
  },
  {
    id: 107,
    type: "snippet",
    topic: "react",
    difficulty: "easy",
    prompt: "Which snippet correctly renders a list of names?",
    snippets: [
      {
        id: "a",
        code: `names.map(n => <li key={n.id}>{n.label}</li>)`,
      },
      {
        id: "b",
        code: `names.forEach(n => <li>{n.label}</li>)`,
      },
      {
        id: "c",
        code: `for (const n of names) return <li>{n.label}</li>`,
      },
    ],
    correctId: "a",
    explanation: "`map` returns an array of elements; `forEach` returns undefined. Keys should be stable.",
  },
  {
    id: 108,
    type: "snippet",
    topic: "react",
    difficulty: "medium",
    prompt: "Which snippet correctly cleans up a subscription in `useEffect`?",
    snippets: [
      {
        id: "a",
        code: `useEffect(() => {\n  const id = setInterval(tick, 1000);\n  return () => clearInterval(id);\n}, []);`,
      },
      {
        id: "b",
        code: `useEffect(() => {\n  setInterval(tick, 1000);\n}, []);`,
      },
      {
        id: "c",
        code: `useEffect(() => {\n  clearInterval(setInterval(tick, 1000));\n}, []);`,
      },
    ],
    correctId: "a",
    explanation: "Return a cleanup function from the effect to clear timers/subscriptions.",
  },
  {
    id: 109,
    type: "match",
    topic: "react",
    difficulty: "easy",
    prompt: "Match each hook to its primary use.",
    left: [
      { id: "state", label: "useState" },
      { id: "effect", label: "useEffect" },
      { id: "memo", label: "useMemo" },
      { id: "cb", label: "useCallback" },
    ],
    right: [
      { id: "r1", label: "local component state" },
      { id: "r2", label: "sync with external systems / side effects" },
      { id: "r3", label: "memoize a computed value" },
      { id: "r4", label: "memoize a function identity" },
    ],
    pairs: { state: "r1", effect: "r2", memo: "r3", cb: "r4" },
  },
  {
    id: 110,
    type: "match",
    topic: "react",
    difficulty: "medium",
    prompt: "Match each term to its meaning.",
    left: [
      { id: "props", label: "props" },
      { id: "state", label: "state" },
      { id: "jsx", label: "JSX" },
      { id: "key", label: "key" },
    ],
    right: [
      { id: "r1", label: "inputs from parent (read-only)" },
      { id: "r2", label: "data owned by the component that can change" },
      { id: "r3", label: "syntax sugar for React.createElement" },
      { id: "r4", label: "stable identity hint for list reconciliation" },
    ],
    pairs: { props: "r1", state: "r2", jsx: "r3", key: "r4" },
  },
  {
    id: 111,
    type: "hotspot",
    topic: "react",
    difficulty: "medium",
    prompt: "Click the line that violates the Rules of Hooks.",
    code: `function Profile({ user }) {
  if (!user) return null;
  const [tab, setTab] = useState("info");
  return <div>{tab}</div>;
}`,
    regions: [
      { id: "r1", label: "Line 1: function signature", startLine: 1, endLine: 1 },
      { id: "r2", label: "Line 2: early return before hooks", startLine: 2, endLine: 2 },
      { id: "r3", label: "Line 3: useState after condition", startLine: 3, endLine: 3 },
      { id: "r4", label: "Line 4: return JSX", startLine: 4, endLine: 4 },
    ],
    correctRegionId: "r3",
    explanation:
      "Hooks must not be called after a conditional return; call hooks unconditionally at the top, then branch.",
  },
  {
    id: 112,
    type: "hotspot",
    topic: "react",
    difficulty: "hard",
    prompt: "Click the line that mutates state incorrectly.",
    code: `function TodoList() {
  const [items, setItems] = useState([{ id: 1, text: "A" }]);
  function add() {
    items.push({ id: 2, text: "B" });
    setItems(items);
  }
  return <button onClick={add}>Add</button>;
}`,
    regions: [
      { id: "r1", label: "Line 2: useState", startLine: 2, endLine: 2 },
      { id: "r2", label: "Line 4: items.push mutation", startLine: 4, endLine: 4 },
      { id: "r3", label: "Line 5: setItems(items)", startLine: 5, endLine: 5 },
      { id: "r4", label: "Line 7: button", startLine: 7, endLine: 7 },
    ],
    correctRegionId: "r2",
    explanation: "Do not push into the existing array; create a new array: `setItems([...items, newItem])`.",
  },
  {
    id: 113,
    type: "output",
    topic: "react",
    difficulty: "easy",
    prompt: "After the first click, what count is shown? (type the number)",
    code: `function Counter() {
  const [n, setN] = useState(0);
  return <button onClick={() => setN(n + 1)}>{n}</button>;
}
// initial render shows 0; user clicks once`,
    accept: ["1"],
    explanation: "Initial 0; one increment → 1.",
  },
  {
    id: 114,
    type: "output",
    topic: "react",
    difficulty: "medium",
    prompt: "How many times does `console.log` run on mount in React 18 Strict Mode (development)?",
    code: `useEffect(() => {
  console.log("mounted");
}, []);`,
    accept: ["2", "twice", "two"],
    hint: "Strict Mode double-invokes effects in development to surface unsafe side effects.",
    explanation:
      "In React 18+ Strict Mode (dev), effects mount → cleanup → mount again, so logs often appear twice.",
  },
  {
    id: 115,
    type: "single",
    topic: "react",
    difficulty: "hard",
    prompt: "What is the main purpose of React Context?",
    options: [
      { id: "a", label: "Replace all component state" },
      { id: "b", label: "Share values to deep descendants without prop drilling" },
      { id: "c", label: "Style components with CSS modules" },
      { id: "d", label: "Compile JSX to HTML on the server only" },
    ],
    correctId: "b",
    explanation: "Context provides a value to a subtree without passing props through every level.",
  },
];
