import type { QuizQuestion } from "../types.ts";

export const tailwindQuestions: QuizQuestion[] = [
  {
    id: 61,
    type: "single",
    topic: "tailwind",
    difficulty: "easy",
    prompt: "What is Tailwind CSS primarily?",
    options: [
      { id: "a", label: "A component library like Material UI" },
      { id: "b", label: "A utility-first CSS framework" },
      { id: "c", label: "A JavaScript animation engine" },
      { id: "d", label: "A CSS-in-JS runtime only" },
    ],
    correctId: "b",
    explanation: "Tailwind provides low-level utility classes you compose in markup.",
  },
  {
    id: 62,
    type: "single",
    topic: "tailwind",
    difficulty: "easy",
    prompt: "Which class sets `display: flex`?",
    options: [
      { id: "a", label: "d-flex" },
      { id: "b", label: "flex" },
      { id: "c", label: "display-flex" },
      { id: "d", label: "flexbox" },
    ],
    correctId: "b",
    explanation: "`flex` maps to `display: flex`.",
  },
  {
    id: 63,
    type: "single",
    topic: "tailwind",
    difficulty: "medium",
    prompt: "What does `md:flex` mean?",
    options: [
      { id: "a", label: "Always flex, medium font" },
      { id: "b", label: "Apply flex at the medium breakpoint and up" },
      { id: "c", label: "Flex only on mobile" },
      { id: "d", label: "Max-width flex container" },
    ],
    correctId: "b",
    explanation: "Responsive prefixes apply styles from that breakpoint upward (mobile-first).",
  },
  {
    id: 64,
    type: "single",
    topic: "tailwind",
    difficulty: "medium",
    prompt: "Which pair correctly adds horizontal padding of 1rem (assuming default spacing scale)?",
    options: [
      { id: "a", label: "px-4" },
      { id: "b", label: "p-x-4" },
      { id: "c", label: "padding-x-4" },
      { id: "d", label: "ph-4" },
    ],
    correctId: "a",
    explanation: "`px-*` is padding-left + padding-right. Default `4` is 1rem.",
  },
  {
    id: 65,
    type: "single",
    topic: "tailwind",
    difficulty: "hard",
    prompt: "In Tailwind v4, how are styles commonly configured compared to classic v3 `tailwind.config.js`?",
    options: [
      { id: "a", label: "Only through inline style attributes" },
      { id: "b", label: "Often via CSS-first configuration (e.g. @theme in CSS) alongside tooling" },
      { id: "c", label: "Tailwind v4 removes all configuration" },
      { id: "d", label: "Only through runtime JavaScript calls" },
    ],
    correctId: "b",
    explanation: "Tailwind v4 emphasizes CSS-first setup with `@import \"tailwindcss\"` and `@theme`.",
  },
  {
    id: 66,
    type: "multi",
    topic: "tailwind",
    difficulty: "easy",
    prompt: "Which classes affect text styling? (select all)",
    options: [
      { id: "a", label: "text-center" },
      { id: "b", label: "font-bold" },
      { id: "c", label: "justify-between" },
      { id: "d", label: "text-sm" },
    ],
    correctIds: ["a", "b", "d"],
    explanation: "`justify-between` is a flex/grid alignment utility, not text styling.",
  },
  {
    id: 67,
    type: "multi",
    topic: "tailwind",
    difficulty: "medium",
    prompt: "Which are valid state/variant prefixes in Tailwind? (select all)",
    options: [
      { id: "a", label: "hover:" },
      { id: "b", label: "focus:" },
      { id: "c", label: "dark:" },
      { id: "d", label: "onclick:" },
    ],
    correctIds: ["a", "b", "c"],
    explanation: "There is no `onclick:` variant; use JS for click handlers.",
  },
  {
    id: 68,
    type: "multi",
    topic: "tailwind",
    difficulty: "medium",
    prompt: "Which utilities help with flex layout? (select all)",
    options: [
      { id: "a", label: "items-center" },
      { id: "b", label: "justify-between" },
      { id: "c", label: "gap-4" },
      { id: "d", label: "object-cover" },
    ],
    correctIds: ["a", "b", "c"],
    explanation: "`object-cover` is for replaced elements (`object-fit`), not flex alignment.",
  },
  {
    id: 69,
    type: "boolean",
    topic: "tailwind",
    difficulty: "easy",
    prompt: "Tailwind is mobile-first: unprefixed utilities apply to all sizes, and `md:` styles apply from the md breakpoint up.",
    correct: true,
    explanation: "Write base (mobile) styles first, then layer larger breakpoints.",
  },
  {
    id: 70,
    type: "boolean",
    topic: "tailwind",
    difficulty: "medium",
    prompt: "You must write a custom CSS file for every button color; utilities cannot style background colors.",
    correct: false,
    explanation: "Utilities like `bg-blue-500` or theme colors style backgrounds without custom CSS for common cases.",
  },
  {
    id: 71,
    type: "boolean",
    topic: "tailwind",
    difficulty: "easy",
    prompt: "`hidden` sets `display: none`.",
    correct: true,
    explanation: "`hidden` is the utility for `display: none`.",
  },
  {
    id: 72,
    type: "fill",
    topic: "tailwind",
    difficulty: "easy",
    prompt: "What class makes an element a CSS Grid container?",
    accept: ["grid"],
    placeholder: "class name",
    explanation: "`grid` → `display: grid`.",
  },
  {
    id: 73,
    type: "fill",
    topic: "tailwind",
    difficulty: "medium",
    prompt: "What class sets `width: 100%`?",
    accept: ["w-full"],
    explanation: "`w-full` is full width of the parent.",
  },
  {
    id: 74,
    type: "fill",
    topic: "tailwind",
    difficulty: "medium",
    prompt: "Complete the class for medium screens and up: `____:text-lg` (breakpoint prefix only).",
    accept: ["md"],
    placeholder: "md",
    explanation: "`md:text-lg` applies larger text from the md breakpoint upward.",
  },
  {
    id: 75,
    type: "order",
    topic: "tailwind",
    difficulty: "medium",
    prompt:
      "A common authoring habit is layout → spacing → typography. Order these class groups that way (note: class order in HTML does not change utility CSS priority):",
    items: [
      { id: "layout", label: "flex flex-col" },
      { id: "space", label: "p-4 gap-2" },
      { id: "type", label: "text-sm text-slate-700" },
    ],
    correctOrder: ["layout", "space", "type"],
    explanation:
      "This is a readability convention only. Among Tailwind utilities, source order in the generated CSS (and conflicts) matter more than the order of classes in the `class` attribute.",
  },
  {
    id: 76,
    type: "order",
    topic: "tailwind",
    difficulty: "easy",
    prompt: "Order the responsive prefixes from smallest breakpoint to largest (default Tailwind screens):",
    items: [
      { id: "sm", label: "sm:" },
      { id: "md", label: "md:" },
      { id: "lg", label: "lg:" },
    ],
    correctOrder: ["sm", "md", "lg"],
    explanation: "Default: sm < md < lg < xl < 2xl.",
  },
  {
    id: 77,
    type: "snippet",
    topic: "tailwind",
    difficulty: "easy",
    prompt: "Which markup correctly centers a flex child horizontally and vertically in a full-height box?",
    snippets: [
      {
        id: "a",
        code: `<div class="flex h-screen items-center justify-center">…</div>`,
      },
      {
        id: "b",
        code: `<div class="flex h-screen content-center">…</div>`,
      },
      {
        id: "c",
        code: `<div class="block h-screen text-center align-middle">…</div>`,
      },
    ],
    correctId: "a",
    explanation: "`items-center` + `justify-center` on a flex container centers on both axes.",
  },
  {
    id: 78,
    type: "snippet",
    topic: "tailwind",
    difficulty: "medium",
    prompt: "Which snippet applies a hover background change correctly?",
    snippets: [
      { id: "a", code: `class="bg-white hover:bg-slate-100"` },
      { id: "b", code: `class="bg-white:hover bg-slate-100"` },
      { id: "c", code: `class="hover bg-white bg-slate-100"` },
    ],
    correctId: "a",
    explanation: "Variants prefix the utility: `hover:bg-slate-100`.",
  },
  {
    id: 79,
    type: "match",
    topic: "tailwind",
    difficulty: "easy",
    prompt: "Match each utility to its CSS effect.",
    left: [
      { id: "m4", label: "m-4" },
      { id: "mt2", label: "mt-2" },
      { id: "rounded", label: "rounded-lg" },
      { id: "shadow", label: "shadow-md" },
    ],
    right: [
      { id: "r1", label: "margin on all sides" },
      { id: "r2", label: "margin-top" },
      { id: "r3", label: "border-radius" },
      { id: "r4", label: "box-shadow" },
    ],
    pairs: { m4: "r1", mt2: "r2", rounded: "r3", shadow: "r4" },
  },
  {
    id: 80,
    type: "match",
    topic: "tailwind",
    difficulty: "medium",
    prompt: "Match each class to its purpose.",
    left: [
      { id: "sr", label: "sr-only" },
      { id: "truncate", label: "truncate" },
      { id: "relative", label: "relative" },
      { id: "z10", label: "z-10" },
    ],
    right: [
      { id: "r1", label: "visually hide but keep for screen readers" },
      { id: "r2", label: "ellipsis overflow for single-line text" },
      { id: "r3", label: "position: relative" },
      { id: "r4", label: "z-index: 10" },
    ],
    pairs: { sr: "r1", truncate: "r2", relative: "r3", z10: "r4" },
  },
  {
    id: 81,
    type: "hotspot",
    topic: "tailwind",
    difficulty: "medium",
    prompt: "Click the line with an invalid / non-standard Tailwind class for horizontal margin auto centering.",
    code: `<div class="mx-auto w-96">
  <p class="text-center">Title</p>
  <button class="margin-x-auto">OK</button>
  <span class="block">Done</span>
</div>`,
    regions: [
      { id: "r1", label: "Line 1: mx-auto container", startLine: 1, endLine: 1 },
      { id: "r2", label: "Line 2: text-center", startLine: 2, endLine: 2 },
      { id: "r3", label: "Line 3: margin-x-auto", startLine: 3, endLine: 3 },
      { id: "r4", label: "Line 4: block", startLine: 4, endLine: 4 },
    ],
    correctRegionId: "r3",
    explanation: "Use `mx-auto`, not `margin-x-auto`.",
  },
  {
    id: 82,
    type: "hotspot",
    topic: "tailwind",
    difficulty: "hard",
    prompt: "Click the line where a conflicting pair likely fights for the same property (last in CSS generation wins, not source order of classes).",
    code: `<button class="px-2 px-8 bg-blue-500 text-white">
  Save
</button>
<span class="text-sm">hint</span>`,
    regions: [
      { id: "r1", label: "Line 1: px-2 and px-8 together", startLine: 1, endLine: 1 },
      { id: "r2", label: "Line 2: Save text", startLine: 2, endLine: 2 },
      { id: "r3", label: "Line 3: closing button", startLine: 3, endLine: 3 },
      { id: "r4", label: "Line 4: text-sm", startLine: 4, endLine: 4 },
    ],
    correctRegionId: "r1",
    explanation: "Avoid conflicting utilities like `px-2` and `px-8` on the same element.",
  },
  {
    id: 83,
    type: "output",
    topic: "tailwind",
    difficulty: "easy",
    prompt: "Which CSS property does `font-bold` primarily set? (answer the property name)",
    code: `/* class: font-bold */`,
    accept: ["font-weight", "fontWeight"],
    explanation: "`font-bold` sets `font-weight: 700`.",
  },
  {
    id: 84,
    type: "output",
    topic: "tailwind",
    difficulty: "medium",
    prompt: "What CSS does `flex-1` roughly correspond to? Type the main declaration value or shorthand people associate (e.g. `1 1 0%` or `flex: 1`).",
    code: `/* class: flex-1 */`,
    accept: ["flex: 1 1 0%", "1 1 0%", "flex: 1", "flex:1"],
    explanation: "`flex-1` is typically `flex: 1 1 0%` so the item can grow/shrink.",
  },
  {
    id: 85,
    type: "single",
    topic: "tailwind",
    difficulty: "hard",
    prompt: "What does the `group` / `group-hover:` pattern enable?",
    options: [
      { id: "a", label: "Style a child when a parent with `group` is hovered" },
      { id: "b", label: "Group CSS files at build time only" },
      { id: "c", label: "Create React context groups" },
      { id: "d", label: "Disable hover on mobile automatically" },
    ],
    correctId: "a",
    explanation: "Mark a parent `group` and use `group-hover:` on descendants to react to parent hover.",
  },
];
