import type { QuizQuestion } from "../types.ts";

export const typescriptQuestions: QuizQuestion[] = [
  {
    id: 31,
    type: "single",
    topic: "typescript",
    difficulty: "easy",
    prompt: "What does TypeScript primarily add on top of JavaScript?",
    options: [
      { id: "a", label: "A new runtime engine" },
      { id: "b", label: "Static typing and compile-time checks" },
      { id: "c", label: "A built-in database driver" },
      { id: "d", label: "Mandatory classes only" },
    ],
    correctId: "b",
    explanation: "TS is a typed superset that erases types when compiling to JavaScript.",
  },
  {
    id: 32,
    type: "single",
    topic: "typescript",
    difficulty: "easy",
    prompt: "Which annotation correctly types a string variable?",
    options: [
      { id: "a", label: "let name: String = \"Ada\";" },
      { id: "b", label: "let name: string = \"Ada\";" },
      { id: "c", label: "let name = string(\"Ada\");" },
      { id: "d", label: "let name as string = \"Ada\";" },
    ],
    correctId: "b",
    explanation: "Prefer primitive types (`string`, `number`, `boolean`) over wrapper object types.",
  },
  {
    id: 33,
    type: "single",
    topic: "typescript",
    difficulty: "medium",
    prompt: "What is the difference between `interface` and `type` aliases for object shapes?",
    options: [
      { id: "a", label: "Interfaces can be declaration-merged; type aliases cannot" },
      { id: "b", label: "Types only work at runtime" },
      { id: "c", label: "Interfaces cannot describe objects" },
      { id: "d", label: "There is no difference at all" },
    ],
    correctId: "a",
    explanation:
      "Both can describe object shapes. Interfaces support declaration merging; type aliases are more flexible for unions/tuples/etc.",
  },
  {
    id: 34,
    type: "single",
    topic: "typescript",
    difficulty: "medium",
    prompt: "What does the `?` mean in `function f(x?: number)`?",
    options: [
      { id: "a", label: "x must be null" },
      { id: "b", label: "x is optional (may be undefined)" },
      { id: "c", label: "x is a Promise" },
      { id: "d", label: "x is readonly" },
    ],
    correctId: "b",
    explanation: "Optional parameters may be omitted; their type includes `undefined`.",
  },
  {
    id: 35,
    type: "single",
    topic: "typescript",
    difficulty: "hard",
    prompt: "What is a discriminated union useful for?",
    options: [
      { id: "a", label: "Merging CSS classes" },
      { id: "b", label: "Narrowing a union via a common literal property (e.g. kind/type)" },
      { id: "c", label: "Speeding up the JS runtime" },
      { id: "d", label: "Declaring global variables only" },
    ],
    correctId: "b",
    explanation:
      "A shared discriminant field lets TS narrow which variant you have inside switch/if branches.",
  },
  {
    id: 36,
    type: "multi",
    topic: "typescript",
    difficulty: "easy",
    prompt: "Which are valid TypeScript primitive type keywords? (select all)",
    options: [
      { id: "a", label: "string" },
      { id: "b", label: "number" },
      { id: "c", label: "integer" },
      { id: "d", label: "boolean" },
      { id: "e", label: "bigint" },
    ],
    correctIds: ["a", "b", "d", "e"],
    explanation: "There is no `integer` type in TypeScript; use `number` or `bigint`.",
  },
  {
    id: 37,
    type: "multi",
    topic: "typescript",
    difficulty: "medium",
    prompt: "Which utility types are built into TypeScript? (select all)",
    options: [
      { id: "a", label: "Partial<T>" },
      { id: "b", label: "Pick<T, K>" },
      { id: "c", label: "Optionalize<T>" },
      { id: "d", label: "Record<K, V>" },
    ],
    correctIds: ["a", "b", "d"],
    explanation: "`Partial`, `Pick`, and `Record` are standard utilities. `Optionalize` is not.",
  },
  {
    id: 38,
    type: "multi",
    topic: "typescript",
    difficulty: "medium",
    prompt: "Which statements about `any` vs `unknown` are true? (select all)",
    options: [
      { id: "a", label: "any disables most type checking on that value" },
      { id: "b", label: "unknown forces you to narrow before using the value" },
      { id: "c", label: "unknown is assignable to every type without checks" },
      { id: "d", label: "Prefer unknown over any when the type is not yet known" },
    ],
    correctIds: ["a", "b", "d"],
    explanation: "`unknown` is the type-safe counterpart of `any`; you must narrow before use.",
  },
  {
    id: 39,
    type: "boolean",
    topic: "typescript",
    difficulty: "easy",
    prompt: "Type annotations are erased when TypeScript is compiled to JavaScript.",
    correct: true,
    explanation: "Types exist only at compile time; the emitted JS has no type annotations.",
  },
  {
    id: 40,
    type: "boolean",
    topic: "typescript",
    difficulty: "medium",
    prompt: "`enum` values always exist only at compile time and never appear in the emitted JavaScript.",
    correct: false,
    explanation:
      "Numeric/string enums emit runtime objects (unless you use `const enum` / alternatives). Prefer union literals for many cases.",
  },
  {
    id: 41,
    type: "boolean",
    topic: "typescript",
    difficulty: "easy",
    prompt: "A variable typed as `string | null` can be passed where a plain `string` is required without narrowing.",
    correct: false,
    explanation: "You must narrow (e.g. null check) or use non-null assertion carefully before treating it as `string`.",
  },
  {
    id: 42,
    type: "fill",
    topic: "typescript",
    difficulty: "easy",
    prompt: "What keyword defines a named object shape that can be implemented by a class?",
    accept: ["interface"],
    placeholder: "keyword",
    explanation: "`interface` describes a contract; classes can `implements` it.",
  },
  {
    id: 43,
    type: "fill",
    topic: "typescript",
    difficulty: "medium",
    prompt: "Complete the utility: `ReadonlyArray<string>` is roughly equivalent to `____ string[]` (modifier + type).",
    accept: ["readonly string[]", "readonly string []"],
    placeholder: "e.g. readonly string[]",
    explanation: "Readonly arrays cannot be mutated via push/pop/etc. at the type level.",
  },
  {
    id: 44,
    type: "fill",
    topic: "typescript",
    difficulty: "medium",
    prompt: "What operator asserts a more specific type (use carefully): `value ____ HTMLElement`?",
    accept: ["as"],
    placeholder: "keyword",
    explanation: "`as` is a type assertion; it does not perform runtime conversion.",
  },
  {
    id: 45,
    type: "order",
    topic: "typescript",
    difficulty: "medium",
    prompt: "Order the steps of a typical TypeScript build pipeline:",
    items: [
      { id: "write", label: "Write .ts source with types" },
      { id: "check", label: "tsc type-checks and emits JS" },
      { id: "run", label: "Run/bundle the emitted JavaScript" },
    ],
    correctOrder: ["write", "check", "run"],
    explanation: "Types are checked at compile time; runtime only sees JS.",
  },
  {
    id: 46,
    type: "order",
    topic: "typescript",
    difficulty: "hard",
    prompt: "Order these from most permissive to most precise typing of an unknown JSON field:",
    items: [
      { id: "any", label: "any" },
      { id: "unknown", label: "unknown" },
      { id: "narrow", label: "unknown + type guard → concrete type" },
    ],
    correctOrder: ["any", "unknown", "narrow"],
    explanation: "`any` is loosest; `unknown` is safe but unusable until narrowed to a concrete type.",
  },
  {
    id: 47,
    type: "snippet",
    topic: "typescript",
    difficulty: "easy",
    prompt: "Which snippet correctly types a function that returns a number?",
    snippets: [
      { id: "a", code: `function add(a: number, b: number): number {\n  return a + b;\n}` },
      { id: "b", code: `function add(a, b): number {\n  return a + b;\n}` },
      { id: "c", code: `function add(a: number, b: number): string {\n  return a + b;\n}` },
    ],
    correctId: "a",
    explanation: "Parameters and return type should be annotated (or inferred consistently).",
  },
  {
    id: 48,
    type: "snippet",
    topic: "typescript",
    difficulty: "medium",
    prompt: "Which snippet correctly defines a readonly tuple of two numbers?",
    snippets: [
      { id: "a", code: `type Point = [number, number];` },
      { id: "b", code: `type Point = readonly [number, number];` },
      { id: "c", code: `type Point = Array<number> & { length: 2 };` },
    ],
    correctId: "b",
    explanation: "`readonly [number, number]` is a readonly tuple; (a) is a mutable tuple.",
  },
  {
    id: 49,
    type: "match",
    topic: "typescript",
    difficulty: "easy",
    prompt: "Match each TypeScript concept to its meaning.",
    left: [
      { id: "union", label: "A | B" },
      { id: "inter", label: "A & B" },
      { id: "gen", label: "<T>" },
      { id: "lit", label: "\"admin\" | \"user\"" },
    ],
    right: [
      { id: "r1", label: "value is A or B" },
      { id: "r2", label: "value has both A and B" },
      { id: "r3", label: "generic type parameter" },
      { id: "r4", label: "string literal union" },
    ],
    pairs: { union: "r1", inter: "r2", gen: "r3", lit: "r4" },
  },
  {
    id: 50,
    type: "match",
    topic: "typescript",
    difficulty: "medium",
    prompt: "Match each utility type to its effect.",
    left: [
      { id: "partial", label: "Partial<T>" },
      { id: "required", label: "Required<T>" },
      { id: "pick", label: "Pick<T, K>" },
      { id: "omit", label: "Omit<T, K>" },
    ],
    right: [
      { id: "r1", label: "all properties optional" },
      { id: "r2", label: "all properties required" },
      { id: "r3", label: "keep only keys K" },
      { id: "r4", label: "remove keys K" },
    ],
    pairs: { partial: "r1", required: "r2", pick: "r3", omit: "r4" },
  },
  {
    id: 51,
    type: "hotspot",
    topic: "typescript",
    difficulty: "medium",
    prompt: "Click the line that is a type error (strict mode).",
    code: `function greet(name: string) {
  return "Hello " + name;
}
greet(null);
const ok = greet("Ada");`,
    regions: [
      { id: "r1", label: "Line 1: function signature", startLine: 1, endLine: 1 },
      { id: "r2", label: "Line 2: return", startLine: 2, endLine: 2 },
      { id: "r3", label: "Line 4: greet(null)", startLine: 4, endLine: 4 },
      { id: "r4", label: "Line 5: greet(\"Ada\")", startLine: 5, endLine: 5 },
    ],
    correctRegionId: "r3",
    explanation: "Under strictNullChecks, `null` is not assignable to `string`.",
  },
  {
    id: 52,
    type: "hotspot",
    topic: "typescript",
    difficulty: "hard",
    prompt: "Click the line that incorrectly uses a type assertion in a way that hides a real mismatch risk.",
    code: `const data: unknown = JSON.parse("{}");
const user = data as { name: string };
console.log(user.name.toUpperCase());
const n: number = 1;`,
    regions: [
      { id: "r1", label: "Line 1: unknown data", startLine: 1, endLine: 1 },
      { id: "r2", label: "Line 2: unsafe assertion", startLine: 2, endLine: 2 },
      { id: "r3", label: "Line 3: use name", startLine: 3, endLine: 3 },
      { id: "r4", label: "Line 4: number", startLine: 4, endLine: 4 },
    ],
    correctRegionId: "r2",
    explanation:
      "Asserting `unknown` to a concrete shape without validation can crash at runtime if the JSON shape differs.",
  },
  {
    id: 53,
    type: "output",
    topic: "typescript",
    difficulty: "easy",
    prompt: "After compilation, what runtime type does this have?\n\n```ts\nconst x: number = 42;\nconsole.log(typeof x);\n```",
    code: `const x: number = 42;\nconsole.log(typeof x);`,
    accept: ['"number"', "number"],
    explanation: "Types erase; at runtime `x` is still a JS number.",
  },
  {
    id: 54,
    type: "output",
    topic: "typescript",
    difficulty: "medium",
    prompt: "What does this type alias describe? Answer with the TypeScript type of `v` after assignment:\n\n```ts\ntype Id = string | number;\nconst v: Id = \"a1\";\n```\n(Write the narrowed type of the value as a string literal type or leave as Id — accept either precise answer)",
    code: `type Id = string | number;\nconst v: Id = "a1";`,
    accept: ["string", '"a1"', "Id"],
    explanation:
      "Annotated as `Id`, but the initializer is a string (and can be inferred more narrowly depending on context).",
  },
  {
    id: 55,
    type: "single",
    topic: "typescript",
    difficulty: "hard",
    prompt: "What does `satisfies` do (TS 4.9+)?",
    options: [
      { id: "a", label: "Checks a value matches a type while preserving the more specific inferred type" },
      { id: "b", label: "Casts a value and changes its runtime representation" },
      { id: "c", label: "Disables type checking for one line" },
      { id: "d", label: "Creates a runtime validator" },
    ],
    correctId: "a",
    explanation:
      "`satisfies` validates assignability without widening to the target type the way a plain annotation can.",
  },
];
