import type { DesignEdge, DesignGraph, DesignNode, EdgeKind } from "./types.ts";

export type SolutionLevel = "simple" | "intermediate" | "advanced";

export const SOLUTION_LEVELS: SolutionLevel[] = [
  "simple",
  "intermediate",
  "advanced",
];

export const SOLUTION_LEVEL_LABELS: Record<SolutionLevel, string> = {
  simple: "Simple",
  intermediate: "Intermediate",
  advanced: "Advanced",
};

function n(
  id: string,
  componentId: string,
  x: number,
  y: number
): DesignNode {
  return { id, componentId, position: { x, y } };
}

function e(
  source: string,
  target: string,
  kind: EdgeKind = "request"
): DesignEdge {
  return { id: `${source}->${target}`, source, target, kind };
}

function cloneGraph(g: DesignGraph): DesignGraph {
  return {
    nodes: g.nodes.map((node) => ({
      ...node,
      position: { ...node.position },
    })),
    edges: g.edges.map((edge) => ({ ...edge })),
  };
}

type TieredSolution = Record<SolutionLevel, DesignGraph>;

/** Official reference designs for `?cheat=1` — three depth levels per challenge. */
export const referenceSolutions: Record<string, TieredSolution> = {
  "realtime-chat": {
    simple: {
      nodes: [
        n("client", "client", 40, 160),
        n("lb", "load-balancer", 200, 160),
        n("api", "api-gateway", 360, 160),
        n("chat", "chat-service", 540, 160),
        n("ws", "websocket-gateway", 360, 300),
        n("queue", "message-queue", 720, 160),
        n("cache", "cache", 720, 280),
        n("db", "database", 900, 280),
      ],
      edges: [
        e("client", "lb"),
        e("lb", "api"),
        e("api", "chat"),
        e("client", "ws"),
        e("chat", "ws"),
        e("chat", "queue", "async"),
        e("chat", "cache", "data"),
        e("cache", "db", "data"),
      ],
    },
    intermediate: {
      nodes: [
        n("client", "client", 40, 160),
        n("lb", "load-balancer", 220, 160),
        n("api", "api-gateway", 400, 160),
        n("auth", "auth-service", 580, 40),
        n("chat", "chat-service", 580, 160),
        n("presence", "presence-service", 580, 280),
        n("ws", "websocket-gateway", 400, 320),
        n("notify", "notification-service", 760, 40),
        n("queue", "message-queue", 760, 160),
        n("cache", "cache", 760, 280),
        n("db", "database", 940, 280),
        n("mon", "monitoring", 400, 40),
      ],
      edges: [
        e("client", "lb"),
        e("lb", "api"),
        e("api", "auth"),
        e("api", "chat"),
        e("chat", "presence"),
        e("chat", "ws"),
        e("client", "ws"),
        e("chat", "queue", "async"),
        e("queue", "notify", "async"),
        e("chat", "cache", "data"),
        e("cache", "db", "data"),
        e("api", "mon", "observe"),
        e("chat", "mon", "observe"),
      ],
    },
    advanced: {
      nodes: [
        n("client", "client", 40, 180),
        n("cdn", "cdn", 200, 40),
        n("lb", "load-balancer", 200, 180),
        n("api", "api-gateway", 360, 180),
        n("auth", "auth-service", 540, 40),
        n("chat", "chat-service", 540, 180),
        n("presence", "presence-service", 540, 300),
        n("ws", "websocket-gateway", 360, 340),
        n("notify", "notification-service", 720, 40),
        n("queue", "message-queue", 720, 140),
        n("worker", "worker", 900, 140),
        n("cache", "cache", 720, 280),
        n("db", "database", 900, 280),
        n("mon", "monitoring", 360, 40),
        n("analytics", "analytics", 900, 40),
      ],
      edges: [
        e("client", "cdn"),
        e("client", "lb"),
        e("lb", "api"),
        e("api", "auth"),
        e("api", "chat"),
        e("chat", "presence"),
        e("chat", "ws"),
        e("client", "ws"),
        e("chat", "queue", "async"),
        e("queue", "worker", "async"),
        e("queue", "notify", "async"),
        e("worker", "notify", "async"),
        e("chat", "cache", "data"),
        e("cache", "db", "data"),
        e("api", "mon", "observe"),
        e("chat", "mon", "observe"),
        e("worker", "analytics", "observe"),
      ],
    },
  },

  "url-shortener": {
    simple: {
      nodes: [
        n("client", "client", 40, 140),
        n("lb", "load-balancer", 220, 140),
        n("api", "api-gateway", 400, 140),
        n("cache", "cache", 580, 140),
        n("db", "database", 760, 140),
        n("mon", "monitoring", 400, 280),
      ],
      edges: [
        e("client", "lb"),
        e("lb", "api"),
        e("api", "cache", "data"),
        e("cache", "db", "data"),
        e("api", "mon", "observe"),
      ],
    },
    intermediate: {
      nodes: [
        n("client", "client", 40, 140),
        n("cdn", "cdn", 220, 60),
        n("lb", "load-balancer", 220, 200),
        n("api", "api-gateway", 400, 140),
        n("cache", "cache", 580, 140),
        n("db", "database", 760, 140),
        n("mon", "monitoring", 400, 280),
      ],
      edges: [
        e("client", "cdn"),
        e("client", "lb"),
        e("cdn", "api"),
        e("lb", "api"),
        e("api", "cache", "data"),
        e("cache", "db", "data"),
        e("api", "mon", "observe"),
      ],
    },
    advanced: {
      nodes: [
        n("client", "client", 40, 160),
        n("cdn", "cdn", 200, 40),
        n("lb", "load-balancer", 200, 180),
        n("api", "api-gateway", 380, 160),
        n("cache", "cache", 560, 160),
        n("db", "database", 740, 160),
        n("queue", "message-queue", 560, 300),
        n("worker", "worker", 740, 300),
        n("analytics", "analytics", 920, 300),
        n("mon", "monitoring", 380, 300),
      ],
      edges: [
        e("client", "cdn"),
        e("client", "lb"),
        e("cdn", "api"),
        e("lb", "api"),
        e("api", "cache", "data"),
        e("cache", "db", "data"),
        e("api", "queue", "async"),
        e("queue", "worker", "async"),
        e("worker", "analytics", "async"),
        e("api", "mon", "observe"),
        e("worker", "mon", "observe"),
      ],
    },
  },

  "news-feed": {
    simple: {
      nodes: [
        n("client", "client", 40, 160),
        n("lb", "load-balancer", 200, 160),
        n("api", "api-gateway", 360, 160),
        n("feed", "feed-service", 540, 160),
        n("queue", "message-queue", 720, 80),
        n("worker", "worker", 900, 80),
        n("cache", "cache", 720, 240),
        n("db", "database", 900, 240),
      ],
      edges: [
        e("client", "lb"),
        e("lb", "api"),
        e("api", "feed"),
        e("feed", "queue", "async"),
        e("queue", "worker", "async"),
        e("feed", "cache", "data"),
        e("cache", "db", "data"),
      ],
    },
    intermediate: {
      nodes: [
        n("client", "client", 40, 160),
        n("cdn", "cdn", 200, 40),
        n("lb", "load-balancer", 200, 160),
        n("api", "api-gateway", 380, 160),
        n("feed", "feed-service", 560, 160),
        n("queue", "message-queue", 740, 80),
        n("worker", "worker", 920, 80),
        n("cache", "cache", 740, 200),
        n("db", "database", 920, 200),
        n("mon", "monitoring", 380, 300),
      ],
      edges: [
        e("client", "cdn"),
        e("client", "lb"),
        e("lb", "api"),
        e("api", "feed"),
        e("feed", "queue", "async"),
        e("queue", "worker", "async"),
        e("worker", "cache", "data"),
        e("feed", "cache", "data"),
        e("cache", "db", "data"),
        e("feed", "mon", "observe"),
      ],
    },
    advanced: {
      nodes: [
        n("client", "client", 40, 180),
        n("cdn", "cdn", 200, 40),
        n("lb", "load-balancer", 200, 180),
        n("api", "api-gateway", 360, 180),
        n("feed", "feed-service", 540, 180),
        n("queue", "message-queue", 720, 60),
        n("worker", "worker", 900, 60),
        n("notify", "notification-service", 900, 160),
        n("cache", "cache", 720, 240),
        n("db", "database", 900, 280),
        n("mon", "monitoring", 360, 320),
        n("analytics", "analytics", 540, 320),
      ],
      edges: [
        e("client", "cdn"),
        e("client", "lb"),
        e("lb", "api"),
        e("api", "feed"),
        e("feed", "queue", "async"),
        e("queue", "worker", "async"),
        e("queue", "notify", "async"),
        e("worker", "cache", "data"),
        e("feed", "cache", "data"),
        e("cache", "db", "data"),
        e("feed", "mon", "observe"),
        e("worker", "analytics", "observe"),
      ],
    },
  },

  "file-storage": {
    simple: {
      nodes: [
        n("client", "client", 40, 160),
        n("cdn", "cdn", 220, 40),
        n("lb", "load-balancer", 40, 40),
        n("api", "api-gateway", 220, 160),
        n("auth", "auth-service", 400, 60),
        n("s3", "object-storage", 400, 160),
        n("db", "database", 580, 160),
        n("worker", "worker", 400, 280),
        n("mon", "monitoring", 580, 280),
      ],
      edges: [
        e("client", "lb"),
        e("lb", "api"),
        e("client", "cdn"),
        e("cdn", "s3", "data"),
        e("api", "auth"),
        e("api", "s3", "data"),
        e("api", "db", "data"),
        e("api", "mon", "observe"),
      ],
    },
    intermediate: {
      nodes: [
        n("client", "client", 40, 160),
        n("cdn", "cdn", 220, 40),
        n("api", "api-gateway", 220, 160),
        n("auth", "auth-service", 400, 60),
        n("s3", "object-storage", 400, 160),
        n("db", "database", 580, 160),
        n("worker", "worker", 400, 280),
        n("queue", "message-queue", 220, 280),
        n("mon", "monitoring", 580, 280),
        n("lb", "load-balancer", 40, 40),
        n("cache", "cache", 580, 40),
      ],
      edges: [
        e("client", "lb"),
        e("lb", "api"),
        e("client", "cdn"),
        e("cdn", "s3", "data"),
        e("api", "auth"),
        e("api", "s3", "data"),
        e("api", "db", "data"),
        e("api", "queue", "async"),
        e("queue", "worker", "async"),
        e("api", "cache", "data"),
        e("cache", "db", "data"),
        e("api", "mon", "observe"),
      ],
    },
    advanced: {
      nodes: [
        n("client", "client", 40, 180),
        n("cdn", "cdn", 200, 40),
        n("lb", "load-balancer", 200, 180),
        n("api", "api-gateway", 380, 180),
        n("auth", "auth-service", 560, 60),
        n("s3", "object-storage", 560, 180),
        n("db", "database", 740, 180),
        n("cache", "cache", 740, 60),
        n("queue", "message-queue", 380, 320),
        n("worker", "worker", 560, 320),
        n("mon", "monitoring", 740, 320),
        n("analytics", "analytics", 920, 320),
      ],
      edges: [
        e("client", "cdn"),
        e("client", "lb"),
        e("lb", "api"),
        e("cdn", "s3", "data"),
        e("api", "auth"),
        e("api", "s3", "data"),
        e("api", "cache", "data"),
        e("cache", "db", "data"),
        e("api", "queue", "async"),
        e("queue", "worker", "async"),
        e("worker", "analytics", "async"),
        e("api", "mon", "observe"),
        e("worker", "mon", "observe"),
      ],
    },
  },

  "ride-matching": {
    simple: {
      nodes: [
        n("client", "client", 40, 180),
        n("lb", "load-balancer", 200, 180),
        n("api", "api-gateway", 360, 180),
        n("ws", "websocket-gateway", 360, 320),
        n("match", "matching-service", 540, 180),
        n("queue", "message-queue", 720, 100),
        n("worker", "worker", 900, 100),
        n("notify", "notification-service", 900, 200),
        n("cache", "cache", 720, 280),
        n("db", "database", 900, 320),
      ],
      edges: [
        e("client", "lb"),
        e("lb", "api"),
        e("api", "match"),
        e("client", "ws"),
        e("match", "ws"),
        e("match", "queue", "async"),
        e("queue", "worker", "async"),
        e("worker", "notify", "async"),
        e("match", "cache", "data"),
        e("cache", "db", "data"),
      ],
    },
    intermediate: {
      nodes: [
        n("client", "client", 40, 180),
        n("lb", "load-balancer", 200, 180),
        n("api", "api-gateway", 360, 180),
        n("ws", "websocket-gateway", 360, 320),
        n("match", "matching-service", 540, 180),
        n("queue", "message-queue", 720, 100),
        n("worker", "worker", 900, 100),
        n("notify", "notification-service", 900, 200),
        n("cache", "cache", 720, 260),
        n("db", "database", 900, 320),
        n("mon", "monitoring", 540, 40),
      ],
      edges: [
        e("client", "lb"),
        e("lb", "api"),
        e("api", "match"),
        e("client", "ws"),
        e("match", "ws"),
        e("match", "queue", "async"),
        e("queue", "worker", "async"),
        e("worker", "notify", "async"),
        e("match", "cache", "data"),
        e("cache", "db", "data"),
        e("match", "mon", "observe"),
      ],
    },
    advanced: {
      nodes: [
        n("client", "client", 40, 180),
        n("cdn", "cdn", 200, 40),
        n("lb", "load-balancer", 200, 180),
        n("api", "api-gateway", 360, 180),
        n("ws", "websocket-gateway", 360, 340),
        n("match", "matching-service", 540, 180),
        n("presence", "presence-service", 540, 300),
        n("queue", "message-queue", 720, 80),
        n("worker", "worker", 900, 80),
        n("notify", "notification-service", 900, 180),
        n("cache", "cache", 720, 260),
        n("db", "database", 900, 320),
        n("mon", "monitoring", 540, 40),
        n("analytics", "analytics", 720, 40),
      ],
      edges: [
        e("client", "cdn"),
        e("client", "lb"),
        e("lb", "api"),
        e("api", "match"),
        e("client", "ws"),
        e("match", "ws"),
        e("match", "presence"),
        e("match", "queue", "async"),
        e("queue", "worker", "async"),
        e("worker", "notify", "async"),
        e("match", "cache", "data"),
        e("cache", "db", "data"),
        e("match", "mon", "observe"),
        e("worker", "analytics", "observe"),
      ],
    },
  },

  "rate-limiter": {
    simple: {
      nodes: [
        n("client", "client", 40, 140),
        n("lb", "load-balancer", 220, 140),
        n("rl", "rate-limiter", 420, 140),
        n("cache", "cache", 620, 140),
        n("mon", "monitoring", 420, 280),
      ],
      edges: [
        e("client", "lb"),
        e("lb", "rl"),
        e("rl", "cache", "data"),
        e("rl", "mon", "observe"),
      ],
    },
    intermediate: {
      nodes: [
        n("client", "client", 40, 140),
        n("lb", "load-balancer", 220, 140),
        n("api", "api-gateway", 400, 140),
        n("rl", "rate-limiter", 580, 140),
        n("cache", "cache", 760, 140),
        n("mon", "monitoring", 580, 280),
      ],
      edges: [
        e("client", "lb"),
        e("lb", "api"),
        e("api", "rl"),
        e("rl", "cache", "data"),
        e("rl", "mon", "observe"),
        e("api", "mon", "observe"),
      ],
    },
    advanced: {
      nodes: [
        n("client", "client", 40, 160),
        n("cdn", "cdn", 200, 40),
        n("lb", "load-balancer", 200, 180),
        n("api", "api-gateway", 380, 160),
        n("rl", "rate-limiter", 560, 160),
        n("cache", "cache", 740, 160),
        n("mon", "monitoring", 560, 300),
        n("analytics", "analytics", 740, 300),
      ],
      edges: [
        e("client", "cdn"),
        e("client", "lb"),
        e("lb", "api"),
        e("api", "rl"),
        e("rl", "cache", "data"),
        e("rl", "mon", "observe"),
        e("api", "mon", "observe"),
        e("rl", "analytics", "observe"),
      ],
    },
  },

  "search-system": {
    simple: {
      nodes: [
        n("client", "client", 40, 160),
        n("lb", "load-balancer", 200, 160),
        n("api", "api-gateway", 360, 160),
        n("search", "search-service", 540, 160),
        n("queue", "message-queue", 720, 60),
        n("worker", "worker", 900, 60),
        n("cache", "cache", 720, 240),
        n("db", "database", 900, 240),
      ],
      edges: [
        e("client", "lb"),
        e("lb", "api"),
        e("api", "search"),
        e("api", "queue", "async"),
        e("queue", "worker", "async"),
        e("search", "cache", "data"),
        e("cache", "db", "data"),
      ],
    },
    intermediate: {
      nodes: [
        n("client", "client", 40, 160),
        n("lb", "load-balancer", 200, 160),
        n("api", "api-gateway", 360, 160),
        n("search", "search-service", 540, 160),
        n("queue", "message-queue", 720, 60),
        n("worker", "worker", 900, 60),
        n("cache", "cache", 720, 220),
        n("db", "database", 900, 220),
        n("mon", "monitoring", 540, 300),
      ],
      edges: [
        e("client", "lb"),
        e("lb", "api"),
        e("api", "search"),
        e("api", "queue", "async"),
        e("queue", "worker", "async"),
        e("search", "cache", "data"),
        e("cache", "db", "data"),
        e("search", "mon", "observe"),
      ],
    },
    advanced: {
      nodes: [
        n("client", "client", 40, 180),
        n("cdn", "cdn", 200, 40),
        n("lb", "load-balancer", 200, 180),
        n("api", "api-gateway", 360, 180),
        n("search", "search-service", 540, 180),
        n("queue", "message-queue", 720, 60),
        n("worker", "worker", 900, 60),
        n("cache", "cache", 720, 220),
        n("db", "database", 900, 220),
        n("mon", "monitoring", 540, 320),
        n("analytics", "analytics", 720, 320),
      ],
      edges: [
        e("client", "cdn"),
        e("client", "lb"),
        e("lb", "api"),
        e("api", "search"),
        e("api", "queue", "async"),
        e("queue", "worker", "async"),
        e("search", "cache", "data"),
        e("cache", "db", "data"),
        e("search", "mon", "observe"),
        e("worker", "analytics", "observe"),
      ],
    },
  },

  "push-notifications": {
    simple: {
      nodes: [
        n("client", "client", 40, 140),
        n("lb", "load-balancer", 200, 140),
        n("api", "api-gateway", 360, 140),
        n("notify", "notification-service", 540, 140),
        n("queue", "message-queue", 720, 80),
        n("worker", "worker", 900, 80),
        n("mon", "monitoring", 540, 280),
      ],
      edges: [
        e("client", "lb"),
        e("lb", "api"),
        e("api", "notify"),
        e("notify", "queue", "async"),
        e("queue", "worker", "async"),
        e("notify", "mon", "observe"),
      ],
    },
    intermediate: {
      nodes: [
        n("client", "client", 40, 140),
        n("lb", "load-balancer", 200, 140),
        n("api", "api-gateway", 360, 140),
        n("notify", "notification-service", 540, 140),
        n("queue", "message-queue", 720, 80),
        n("worker", "worker", 900, 80),
        n("mon", "monitoring", 540, 280),
      ],
      edges: [
        e("client", "lb"),
        e("lb", "api"),
        e("api", "notify"),
        e("notify", "queue", "async"),
        e("queue", "worker", "async"),
        e("notify", "mon", "observe"),
        e("worker", "mon", "observe"),
      ],
    },
    advanced: {
      nodes: [
        n("client", "client", 40, 160),
        n("lb", "load-balancer", 200, 160),
        n("api", "api-gateway", 360, 160),
        n("notify", "notification-service", 540, 160),
        n("queue", "message-queue", 720, 60),
        n("worker", "worker", 900, 60),
        n("cache", "cache", 720, 220),
        n("db", "database", 900, 220),
        n("mon", "monitoring", 540, 300),
        n("analytics", "analytics", 720, 300),
      ],
      edges: [
        e("client", "lb"),
        e("lb", "api"),
        e("api", "notify"),
        e("notify", "queue", "async"),
        e("queue", "worker", "async"),
        e("notify", "cache", "data"),
        e("cache", "db", "data"),
        e("notify", "mon", "observe"),
        e("worker", "mon", "observe"),
        e("worker", "analytics", "observe"),
      ],
    },
  },
};

export function getReferenceSolution(
  challengeId: string,
  level: SolutionLevel = "intermediate"
): DesignGraph | null {
  const tiers = referenceSolutions[challengeId];
  if (!tiers) return null;
  const g = tiers[level];
  return g ? cloneGraph(g) : null;
}

export function hasReferenceSolution(challengeId: string): boolean {
  return Boolean(referenceSolutions[challengeId]);
}
