import type { QuizQuestion } from "../types.ts";

export const architectureQuestions: QuizQuestion[] = [
  {
    id: 331,
    type: "single",
    topic: "architecture",
    difficulty: "easy",
    prompt: "What sits in front of multiple app instances to distribute incoming traffic?",
    options: [
      { id: "a", label: "Load balancer" },
      { id: "b", label: "CSS preprocessor" },
      { id: "c", label: "Source map generator" },
      { id: "d", label: "Unit test runner" },
    ],
    correctId: "a",
    explanation:
      "A load balancer spreads requests across healthy instances so one box is not a single point of overload.",
    illustration: {
      kind: "svg",
      diagram: "load-balancer",
      alt: "Clients connect to a load balancer that fans out to App 1–3",
      caption: "Load balancer fans traffic out to instances",
    },
  },
  {
    id: 332,
    type: "single",
    topic: "architecture",
    difficulty: "easy",
    prompt: "What is the main job of a reverse proxy in a typical web stack?",
    options: [
      { id: "a", label: "Accept client requests and forward them to upstream app servers" },
      { id: "b", label: "Compile TypeScript in the browser" },
      { id: "c", label: "Replace the database entirely" },
      { id: "d", label: "Store passwords in localStorage" },
    ],
    correctId: "a",
    explanation:
      "Clients talk to the proxy; the proxy forwards to app processes (and often handles TLS).",
    illustration: {
      kind: "svg",
      diagram: "reverse-proxy",
      alt: "Internet traffic hits a reverse proxy that forwards to an app process",
      caption: "Reverse proxy sits in front of the app",
    },
  },
  {
    id: 333,
    type: "boolean",
    topic: "architecture",
    difficulty: "easy",
    prompt: "A CDN caches responses closer to users to reduce latency and origin load.",
    correct: true,
    explanation: "Edge caches serve many hits without round-tripping to the origin every time.",
  },
  {
    id: 334,
    type: "single",
    topic: "architecture",
    difficulty: "medium",
    prompt: "On a CDN cache miss, what does the origin server do?",
    options: [
      { id: "a", label: "Serve the source response that the CDN can then cache" },
      { id: "b", label: "Delete all edge nodes" },
      { id: "c", label: "Always return HTTP 451" },
      { id: "d", label: "Compile the client's CSS" },
    ],
    correctId: "a",
    explanation: "Misses go to origin; the CDN may store the response for later hits.",
    illustration: {
      kind: "svg",
      diagram: "cdn-origin",
      alt: "Users hit a CDN which fetches from an origin on miss",
      caption: "CDN miss falls through to origin",
    },
  },
  {
    id: 335,
    type: "single",
    topic: "architecture",
    difficulty: "medium",
    prompt: "In a common production request path, what sits between the client and the app?",
    options: [
      { id: "a", label: "Reverse proxy / edge layer" },
      { id: "b", label: "The user's GPU driver" },
      { id: "c", label: "A desktop printer spooler" },
      { id: "d", label: "Excel macros" },
    ],
    correctId: "a",
    explanation: "Traffic usually hits TLS termination / proxy / edge before application servers.",
    illustration: {
      kind: "svg",
      diagram: "request-path",
      alt: "Client to edge/proxy to app to database",
      caption: "Client → edge/proxy → app → DB",
    },
  },
  {
    id: 336,
    type: "multi",
    topic: "architecture",
    difficulty: "medium",
    prompt: "Which are benefits of horizontal scaling? (select all)",
    options: [
      { id: "a", label: "Add more machines to handle more load" },
      { id: "b", label: "Survive losing a single instance more easily" },
      { id: "c", label: "Guarantees zero network latency" },
      { id: "d", label: "Removes the need for any monitoring" },
    ],
    correctIds: ["a", "b"],
    explanation: "Horizontal scale adds instances; it does not magically erase latency or ops work.",
  },
  {
    id: 337,
    type: "single",
    topic: "architecture",
    difficulty: "easy",
    prompt: "What does vertical scaling usually mean?",
    options: [
      { id: "a", label: "Giving one machine more CPU/RAM" },
      { id: "b", label: "Adding identical machines behind a load balancer" },
      { id: "c", label: "Deleting indexes to save disk" },
      { id: "d", label: "Moving CSS to inline styles" },
    ],
    correctId: "a",
    explanation: "Vertical = bigger box; horizontal = more boxes.",
  },
  {
    id: 338,
    type: "match",
    topic: "architecture",
    difficulty: "medium",
    prompt: "Match each component to its primary role.",
    left: [
      { id: "l1", label: "Load balancer" },
      { id: "l2", label: "CDN" },
      { id: "l3", label: "Reverse proxy" },
      { id: "l4", label: "Message queue" },
    ],
    right: [
      { id: "r1", label: "Fan out requests to app instances" },
      { id: "r2", label: "Cache content near users" },
      { id: "r3", label: "Front apps / terminate client connections" },
      { id: "r4", label: "Decouple producers and consumers asynchronously" },
    ],
    pairs: { l1: "r1", l2: "r2", l3: "r3", l4: "r4" },
    explanation: "Each piece solves a different slice of scale, latency, or decoupling.",
  },
  {
    id: 339,
    type: "order",
    topic: "architecture",
    difficulty: "medium",
    prompt: "Order these hops for a typical web request (first → last).",
    items: [
      { id: "client", label: "Client" },
      { id: "proxy", label: "Reverse proxy / edge" },
      { id: "app", label: "Application server" },
      { id: "db", label: "Database" },
    ],
    correctOrder: ["client", "proxy", "app", "db"],
    explanation: "Clients rarely talk to the database directly in a standard three-tier web app.",
    illustration: {
      kind: "svg",
      diagram: "request-path",
      alt: "Ordered hops from client through proxy and app to DB",
      caption: "Follow the arrows left to right",
    },
  },
  {
    id: 340,
    type: "single",
    topic: "architecture",
    difficulty: "medium",
    prompt: "Why cache responses near the edge (CDN/browser)?",
    options: [
      { id: "a", label: "Lower latency and less load on origin" },
      { id: "b", label: "To force every request through the database twice" },
      { id: "c", label: "To disable HTTPS" },
      { id: "d", label: "To replace automated tests" },
    ],
    correctId: "a",
    explanation: "Edge cache hits are fast and spare the origin.",
    illustration: {
      kind: "svg",
      diagram: "cache-layers",
      alt: "Browser, CDN, app, and DB cache layers",
      caption: "Caches can exist at multiple layers",
    },
  },
  {
    id: 341,
    type: "boolean",
    topic: "architecture",
    difficulty: "medium",
    prompt: "Sticky sessions are always required when using a load balancer.",
    correct: false,
    explanation:
      "Sticky sessions help when local server state exists; stateless apps usually do not need them.",
  },
  {
    id: 342,
    type: "single",
    topic: "architecture",
    difficulty: "hard",
    prompt: "What do load-balancer health checks primarily enable?",
    options: [
      { id: "a", label: "Avoid sending traffic to unhealthy instances" },
      { id: "b", label: "Automatically rewrite SQL queries" },
      { id: "c", label: "Compile Sass" },
      { id: "d", label: "Encrypt the database at rest by themselves" },
    ],
    correctId: "a",
    explanation: "Failed checks remove (or avoid) bad instances from the pool.",
    illustration: {
      kind: "svg",
      diagram: "load-balancer",
      alt: "Load balancer in front of multiple app instances",
      caption: "Only healthy instances should receive traffic",
    },
  },
  {
    id: 343,
    type: "single",
    topic: "architecture",
    difficulty: "medium",
    prompt: "What is a primary tradeoff of a monolith versus many small services?",
    options: [
      { id: "a", label: "Simpler deploy/reasoning vs independent scale and deploy per service" },
      { id: "b", label: "Monoliths cannot use databases" },
      { id: "c", label: "Services never need networking" },
      { id: "d", label: "Monoliths always scale infinitely" },
    ],
    correctId: "a",
    explanation: "Services buy isolation at the cost of operational and distributed complexity.",
  },
  {
    id: 344,
    type: "fill",
    topic: "architecture",
    difficulty: "medium",
    prompt: "What does CDN stand for? (three words)",
    accept: ["content delivery network", "content distribution network"],
    placeholder: "c... d... n...",
    explanation: "CDN = content delivery (sometimes distribution) network.",
  },
  {
    id: 345,
    type: "single",
    topic: "architecture",
    difficulty: "hard",
    prompt: "Which problem is classically hardest about caching?",
    options: [
      { id: "a", label: "Invalidation / keeping cached data fresh enough" },
      { id: "b", label: "Choosing a font for cache keys" },
      { id: "c", label: "Naming the cache folder Desktop" },
      { id: "d", label: "Using arrays instead of objects in JS" },
    ],
    correctId: "a",
    explanation: "Stale or inconsistent cache entries cause subtle production bugs.",
    illustration: {
      kind: "svg",
      diagram: "cache-layers",
      alt: "Multiple cache layers that can serve stale data",
      caption: "Every layer needs a freshness strategy",
    },
  },
  {
    id: 346,
    type: "multi",
    topic: "architecture",
    difficulty: "medium",
    prompt: "Which belong on a typical web request-path diagram? (select all)",
    options: [
      { id: "a", label: "Reverse proxy / edge" },
      { id: "b", label: "Application server" },
      { id: "c", label: "Database" },
      { id: "d", label: "Client-side CSS bundler as a required production hop" },
    ],
    correctIds: ["a", "b", "c"],
    explanation: "Bundlers are build-time; the live path is client → edge/app → data.",
  },
  {
    id: 347,
    type: "single",
    topic: "architecture",
    difficulty: "hard",
    prompt: "When are retries of the same POST request safest?",
    options: [
      { id: "a", label: "When the operation is idempotent (repeat causes no extra side effects)" },
      { id: "b", label: "When the server ignores status codes" },
      { id: "c", label: "When you retry infinitely with no backoff" },
      { id: "d", label: "When cookies are disabled worldwide" },
    ],
    correctId: "a",
    explanation: "Idempotency keys / idempotent semantics prevent duplicate charges or creates.",
  },
  {
    id: 348,
    type: "boolean",
    topic: "architecture",
    difficulty: "easy",
    prompt:
      "In a standard deployment, a reverse proxy faces clients and forwards to app processes behind it.",
    correct: true,
    explanation: "Clients → reverse proxy → app(s).",
    illustration: {
      kind: "svg",
      diagram: "reverse-proxy",
      alt: "Reverse proxy facing the internet with apps behind it",
      caption: "Proxy in front, apps behind",
    },
  },
];
