import type { QuizQuestion } from "../types.ts";

export const devopsQuestions: QuizQuestion[] = [
  {
    id: 365,
    type: "single",
    topic: "devops",
    difficulty: "easy",
    prompt: "What does CI primarily focus on?",
    options: [
      { id: "a", label: "Automatically building and testing changes as they land" },
      { id: "b", label: "Hand-copying zip files to production on Fridays only" },
      { id: "c", label: "Designing logo colors" },
      { id: "d", label: "Writing CSS resets" },
    ],
    correctId: "a",
    explanation: "Continuous Integration keeps mainline healthy with automated build/test feedback.",
    illustration: {
      kind: "svg",
      diagram: "ci-cd-pipeline",
      alt: "Commit to build/test to artifact to deploy pipeline",
      caption: "CI is the early automated verification stages",
    },
  },
  {
    id: 366,
    type: "single",
    topic: "devops",
    difficulty: "easy",
    prompt: "What does CD usually refer to in DevOps conversations?",
    options: [
      { id: "a", label: "Continuous delivery and/or continuous deployment of software" },
      { id: "b", label: "Compact discs only" },
      { id: "c", label: "Cascading deletes in SQL only" },
      { id: "d", label: "Client-side DOM only" },
    ],
    correctId: "a",
    explanation: "CD is about getting validated changes to users safely and often.",
  },
  {
    id: 367,
    type: "boolean",
    topic: "devops",
    difficulty: "easy",
    prompt: "Containers package an application with its dependencies for consistent runtime environments.",
    correct: true,
    explanation: "Images capture deps so \"works on my machine\" issues shrink.",
  },
  {
    id: 368,
    type: "order",
    topic: "devops",
    difficulty: "medium",
    prompt: "Order a simple CI/CD flow (first → last).",
    items: [
      { id: "commit", label: "Commit / push" },
      { id: "test", label: "Build & test" },
      { id: "artifact", label: "Produce artifact/image" },
      { id: "deploy", label: "Deploy" },
    ],
    correctOrder: ["commit", "test", "artifact", "deploy"],
    explanation: "You verify before you ship; artifacts should be what you deploy.",
    illustration: {
      kind: "svg",
      diagram: "ci-cd-pipeline",
      alt: "Pipeline stages from commit through deploy",
      caption: "Follow the pipeline left to right",
    },
  },
  {
    id: 369,
    type: "single",
    topic: "devops",
    difficulty: "medium",
    prompt: "Why put nginx/Caddy (or similar) in front of a Node app?",
    options: [
      { id: "a", label: "TLS termination, static files, and reverse-proxying to the app port" },
      { id: "b", label: "To rewrite TypeScript into COBOL automatically" },
      { id: "c", label: "To remove the need for backups forever" },
      { id: "d", label: "To store JWT secrets in CSS variables" },
    ],
    correctId: "a",
    explanation: "A reverse proxy handles edge concerns while Node focuses on app logic.",
    illustration: {
      kind: "svg",
      diagram: "reverse-proxy",
      alt: "Reverse proxy in front of an app process",
      caption: "Proxy handles the public door",
    },
  },
  {
    id: 370,
    type: "match",
    topic: "devops",
    difficulty: "medium",
    prompt: "Match each observability signal to what it usually answers.",
    left: [
      { id: "l1", label: "Logs" },
      { id: "l2", label: "Metrics" },
      { id: "l3", label: "Traces" },
    ],
    right: [
      { id: "r1", label: "What happened in a specific event/message stream" },
      { id: "r2", label: "Aggregated numbers over time (CPU, RPS, errors)" },
      { id: "r3", label: "How a request flowed across services" },
    ],
    pairs: { l1: "r1", l2: "r2", l3: "r3" },
    explanation: "Logs/metrics/traces complement each other; none replaces the others fully.",
  },
  {
    id: 371,
    type: "single",
    topic: "devops",
    difficulty: "medium",
    prompt: "What is the core idea of blue-green deployment?",
    options: [
      { id: "a", label: "Run two environments and switch traffic from the old to the new" },
      { id: "b", label: "Deploy only when the logo is blue or green" },
      { id: "c", label: "Delete production nightly" },
      { id: "d", label: "Use two databases and never back them up" },
    ],
    correctId: "a",
    explanation: "Traffic flip (or gradual shift) makes rollback a switch back to the previous color.",
    illustration: {
      kind: "svg",
      diagram: "blue-green",
      alt: "Load balancer choosing between green and blue environments",
      caption: "LB points at the active color",
    },
  },
  {
    id: 372,
    type: "boolean",
    topic: "devops",
    difficulty: "medium",
    prompt: "A rolling deploy always updates every instance at the exact same instant.",
    correct: false,
    explanation: "Rolling updates replace instances in batches so some stay up throughout.",
  },
  {
    id: 373,
    type: "single",
    topic: "devops",
    difficulty: "medium",
    prompt: "What is the purpose of a readiness probe?",
    options: [
      { id: "a", label: "Decide when an instance can safely receive traffic" },
      { id: "b", label: "Decide the company's holiday calendar" },
      { id: "c", label: "Format disks on deploy" },
      { id: "d", label: "Choose Tailwind color tokens" },
    ],
    correctId: "a",
    explanation: "Readiness gates traffic; liveness often restarts stuck processes — related but different.",
  },
  {
    id: 374,
    type: "multi",
    topic: "devops",
    difficulty: "medium",
    prompt: "Which should live in env/secret config rather than committed source? (select all)",
    options: [
      { id: "a", label: "Production API keys" },
      { id: "b", label: "Database passwords" },
      { id: "c", label: "The MIT license text" },
      { id: "d", label: "Cloud access tokens" },
    ],
    correctIds: ["a", "b", "d"],
    explanation: "Secrets belong in a secret store / env injection, not git history.",
  },
  {
    id: 375,
    type: "single",
    topic: "devops",
    difficulty: "hard",
    prompt: "What is a risk if blue and green share one destructive migration path incorrectly?",
    options: [
      { id: "a", label: "Both environments can break because they share the bad data change" },
      { id: "b", label: "CSS will stop minifying" },
      { id: "c", label: "Git remotes rename themselves" },
      { id: "d", label: "DNS becomes optional" },
    ],
    correctId: "a",
    explanation: "Environment switching does not save you from unsafe shared-database migrations.",
    illustration: {
      kind: "svg",
      diagram: "blue-green",
      alt: "Two environments behind a load balancer",
      caption: "Shared DB migrations still need care",
    },
  },
  {
    id: 376,
    type: "single",
    topic: "devops",
    difficulty: "easy",
    prompt: "A good build artifact should be:",
    options: [
      { id: "a", label: "Versioned and treated as immutable once produced" },
      { id: "b", label: "Edited by hand on the server after deploy" },
      { id: "c", label: "Different every time someone SSHs in" },
      { id: "d", label: "Stored only in chat screenshots" },
    ],
    correctId: "a",
    explanation: "Immutable artifacts make deploys reproducible and rollbacks meaningful.",
    illustration: {
      kind: "svg",
      diagram: "ci-cd-pipeline",
      alt: "Artifact stage in a CI/CD pipeline",
      caption: "Ship the artifact you tested",
    },
  },
  {
    id: 377,
    type: "fill",
    topic: "devops",
    difficulty: "medium",
    prompt: "Servers you never SSH-mutate, replacing them with new images instead, are often called _____ infrastructure.",
    accept: ["immutable", "immutable infrastructure"],
    placeholder: "im...",
    explanation: "Immutable infrastructure favors replace-over-mutate.",
  },
  {
    id: 378,
    type: "single",
    topic: "devops",
    difficulty: "medium",
    prompt: "Compared to a VM, a container typically:",
    options: [
      { id: "a", label: "Shares the host kernel and is lighter-weight" },
      { id: "b", label: "Always includes a full guest OS kernel per container" },
      { id: "c", label: "Cannot isolate processes at all" },
      { id: "d", label: "Replaces TCP with carrier pigeons" },
    ],
    correctId: "a",
    explanation: "Containers virtualize the process environment; VMs virtualize hardware/OS more heavily.",
  },
  {
    id: 379,
    type: "multi",
    topic: "devops",
    difficulty: "hard",
    prompt: "Which traits make a good health check? (select all)",
    options: [
      { id: "a", label: "Cheap to run frequently" },
      { id: "b", label: "Reflects whether the instance can serve traffic" },
      { id: "c", label: "Flaps randomly every few milliseconds" },
      { id: "d", label: "Avoids depending on unrelated third systems when possible" },
    ],
    correctIds: ["a", "b", "d"],
    explanation: "Noisy or misleading probes cause false evacuations and outages.",
  },
  {
    id: 380,
    type: "boolean",
    topic: "devops",
    difficulty: "easy",
    prompt:
      "In small setups, the app often listens on an internal port while a reverse proxy handles public HTTPS.",
    correct: true,
    explanation: "Proxy terminates TLS and forwards to localhost/private network app ports.",
    illustration: {
      kind: "svg",
      diagram: "reverse-proxy",
      alt: "Public proxy forwarding to an internal app",
      caption: "Public edge, private app port",
    },
  },
];
